In [1]:
%load_ext autoreload
%autoreload 2

import torch
from alpha_connect import AlphaZeroModelConnect4, Trainer
import os

In [2]:
device = torch.device("mps")

args = {
    "batch_size": 128,
    "numIters": 500,  # Total number of training iterations
    "num_simulations": 200,  # Total number of MCTS simulations to run when deciding on a move to play
    "numEps": 128,  # Number of full games (episodes) to run during each iteration
    "numItersForTrainExamplesHistory": 20,
    "epochs": 2,  # Number of epochs of training per iteration
    "checkpoint_path": "../data/latest.pth",  # location to save latest set of weights
    "loss_history_path": "../data/loss_history.csv",  # location to save loss history
    "temperature": 1,  #
}

if os.path.exists(args["checkpoint_path"]):
    model = AlphaZeroModelConnect4()
    model.load_state_dict(torch.load(args["checkpoint_path"]))
    print("Loaded model from checkpoint")
else:
    model = AlphaZeroModelConnect4()
model.to(device)

trainer = Trainer(model, args)
trainer.learn()

1/500


1927it [12:18,  2.61it/s]                        



loss: 3.094891739388307
Policy Loss 0.7022940988341967
Value Loss 0.9880094428857168
Examples:
tensor([ 0.2415,  0.0420, -0.0392,  0.0929,  0.1499,  0.1279,  0.0940])
tensor([1., 0., 0., 0., 0., 0., 0.])
tensor([-0.1834])
tensor(1.)
New best loss: 3.094891739388307
2/500


2174it [09:27,  3.83it/s]                        



loss: 1.5834034872055054
Policy Loss 0.21654011011123658
Value Loss 0.9337831568717957
Examples:
tensor([ 0.1090,  0.1376, -0.0089,  0.1053,  0.2609,  0.1325,  0.2310])
tensor([0.0553, 0.1106, 0.0000, 0.2060, 0.2111, 0.1307, 0.2864])
tensor([-0.0425])
tensor(-1.)
New best loss: 1.5834034872055054
3/500


2737it [08:16,  5.51it/s]                       



loss: 1.5861182317137716
Policy Loss 0.22857849448919296
Value Loss 0.9003827482461929
Examples:
tensor([0.0810, 0.0590, 0.0769, 0.1681, 0.2642, 0.1468, 0.1592])
tensor([0.1156, 0.0603, 0.0000, 0.0905, 0.4874, 0.1357, 0.1106])
tensor([-0.0286])
tensor(1.)
4/500


2859it [08:06,  5.88it/s]                        



loss: 1.4756933646766761
Policy Loss 0.2270236948603078
Value Loss 0.7946222800957529
Examples:
tensor([-0.0134,  0.1048,  0.0202,  0.2275,  0.1865,  0.2108,  0.0926])
tensor([0.0000, 0.3920, 0.0000, 0.0804, 0.1005, 0.3518, 0.0754])
tensor([0.4719])
tensor(-1.)
New best loss: 1.4756933646766761
5/500


2732it [08:41,  5.23it/s]                        



loss: 1.6024274609982967
Policy Loss 0.264419163018465
Value Loss 0.8091699719429016
Examples:
tensor([ 0.1733,  0.2760, -0.0179,  0.0609,  0.0952,  0.2207,  0.2014])
tensor([0.1508, 0.7437, 0.0000, 0.0000, 0.0000, 0.0302, 0.0754])
tensor([0.3102])
tensor(1.)
6/500


2494it [09:09,  4.54it/s]                        



loss: 1.739487805149772
Policy Loss 0.31843766841021454
Value Loss 0.7841747999191284
Examples:
tensor([0.1802, 0.1620, 0.0278, 0.2003, 0.2574, 0.0481, 0.0735])
tensor([0.0000, 0.0151, 0.0000, 0.0000, 0.0302, 0.9447, 0.0101])
tensor([0.2124])
tensor(1.)
7/500


2255it [09:43,  3.87it/s]                        



loss: 1.7516394704580307
Policy Loss 0.3043922384579976
Value Loss 0.8384627550840378
Examples:
tensor([ 0.0752,  0.0647,  0.0518,  0.2611,  0.1697, -0.0735,  0.2254])
tensor([0.1156, 0.3719, 0.1055, 0.0854, 0.1055, 0.0000, 0.2161])
tensor([0.1705])
tensor(-1.)
8/500


2499it [09:01,  4.62it/s]                        



loss: 1.4762395295229824
Policy Loss 0.20347238399765707
Value Loss 0.8658223775300112
Examples:
tensor([ 0.0489,  0.2388, -0.0102,  0.2401,  0.3876, -0.0411,  0.1780])
tensor([0.0452, 0.0603, 0.0251, 0.0503, 0.7789, 0.0000, 0.0402])
tensor([-0.2502])
tensor(1.)
9/500


2551it [09:19,  4.56it/s]                        



loss: 1.483545647426085
Policy Loss 0.22474268078804016
Value Loss 0.8093176050619646
Examples:
tensor([ 0.0514, -0.0035,  0.2149, -0.0957, -0.0095,  0.3012,  0.3146])
tensor([0.0000, 0.0000, 0.1005, 0.0000, 0.0000, 0.4724, 0.4271])
tensor([-0.7080])
tensor(-1.)
10/500


2392it [09:32,  4.18it/s]                        



loss: 1.5850903139166208
Policy Loss 0.25965893722098804
Value Loss 0.8061135022536569
Examples:
tensor([0.1131, 0.2378, 0.1216, 0.2894, 0.1937, 0.1577, 0.2034])
tensor([0.0101, 0.0201, 0.0050, 0.0503, 0.8894, 0.0050, 0.0201])
tensor([0.4844])
tensor(0.)
11/500


2374it [09:41,  4.09it/s]                        



loss: 1.4492242090080096
Policy Loss 0.22260201625202014
Value Loss 0.7814181602519491
Examples:
tensor([ 0.0816,  0.4765,  0.2420,  0.0733,  0.1658, -0.0090, -0.0127])
tensor([0.0151, 0.7588, 0.0704, 0.0251, 0.1106, 0.0101, 0.0101])
tensor([-0.0720])
tensor(-1.)
New best loss: 1.4492242090080096
12/500


2573it [09:05,  4.72it/s]                        



loss: 1.3767450288647698
Policy Loss 0.18092003819488345
Value Loss 0.8339849142801194
Examples:
tensor([0.0143, 0.1927, 0.1406, 0.6188, 0.0473, 0.0102, 0.0479])
tensor([0.0050, 0.0603, 0.1809, 0.6633, 0.0452, 0.0201, 0.0251])
tensor([0.1777])
tensor(1.)
New best loss: 1.3767450288647698
13/500


2811it [08:29,  5.52it/s]                        



loss: 1.3604569673538207
Policy Loss 0.18848148882389068
Value Loss 0.7950125008821487
Examples:
tensor([ 0.1098,  0.3747,  0.2212,  0.0721,  0.1273,  0.2703, -0.0402])
tensor([0.0151, 0.9246, 0.0201, 0.0151, 0.0101, 0.0151, 0.0000])
tensor([0.4491])
tensor(1.)
New best loss: 1.3604569673538207
14/500


2180it [09:59,  3.63it/s]                        



loss: 1.538764232148727
Policy Loss 0.2421162190536658
Value Loss 0.8124155749877294
Examples:
tensor([-0.0181,  0.2494,  0.2528,  0.0146,  0.3101,  0.1522,  0.0653])
tensor([0.0101, 0.1106, 0.0704, 0.0000, 0.7136, 0.0302, 0.0653])
tensor([0.2374])
tensor(-1.)
15/500


2500it [09:13,  4.51it/s]                        



loss: 1.2819122929464686
Policy Loss 0.16252659532156857
Value Loss 0.7943325069817629
Examples:
tensor([0.0556, 0.2610, 0.0855, 0.3276, 0.1191, 0.1066, 0.1130])
tensor([0.1709, 0.2563, 0.0000, 0.2362, 0.1005, 0.1005, 0.1357])
tensor([0.3639])
tensor(-1.)
New best loss: 1.2819122929464686
16/500


2584it [09:11,  4.68it/s]                        



loss: 1.494751520809673
Policy Loss 0.2081074437924794
Value Loss 0.870429189432235
Examples:
tensor([0.0638, 0.1570, 0.3460, 0.0862, 0.2186, 0.1383, 0.0357])
tensor([0.0603, 0.2965, 0.0854, 0.0201, 0.3920, 0.1005, 0.0452])
tensor([0.0202])
tensor(-1.)
17/500


2755it [08:52,  5.18it/s]                       



loss: 1.400640434771776
Policy Loss 0.18663114234805106
Value Loss 0.840747007727623
Examples:
tensor([-0.0392,  0.0150,  0.0406,  0.1460,  0.5254,  0.0358,  0.1360])
tensor([0.0000, 0.0101, 0.1256, 0.1859, 0.4975, 0.0000, 0.1809])
tensor([0.0746])
tensor(1.)
18/500


2688it [08:53,  5.04it/s]                        



loss: 1.325094657994452
Policy Loss 0.1780911535024643
Value Loss 0.7908211974870591
Examples:
tensor([0.0287, 0.3259, 0.2488, 0.0036, 0.0568, 0.3472, 0.1105])
tensor([0.0000, 0.0251, 0.9246, 0.0000, 0.0000, 0.0302, 0.0201])
tensor([-0.1365])
tensor(0.)
19/500


2916it [08:27,  5.75it/s]                       



loss: 1.3994774081205066
Policy Loss 0.18774678048334623
Value Loss 0.8362370666704679
Examples:
tensor([-0.0348, -0.0307, -0.0404,  0.9616, -0.0291,  0.0997,  0.0013])
tensor([0.0050, 0.0050, 0.0000, 0.9196, 0.0000, 0.0452, 0.0251])
tensor([0.1293])
tensor(-1.)
20/500


2906it [08:00,  6.05it/s]                        



loss: 1.3587531719137642
Policy Loss 0.18324724453337052
Value Loss 0.8090114383136525
Examples:
tensor([0.0691, 0.3411, 0.1758, 0.2297, 0.0399, 0.1177, 0.0907])
tensor([0.1859, 0.2915, 0.1357, 0.0251, 0.0603, 0.2111, 0.0905])
tensor([-0.1308])
tensor(-1.)
21/500


2463it [09:30,  4.32it/s]                        



loss: 1.5515423579649492
Policy Loss 0.21994694525545294
Value Loss 0.8917015221985903
Examples:
tensor([-0.0334,  0.1155,  0.0823,  0.0810,  0.4942,  0.0933, -0.0093])
tensor([0.0000, 0.1658, 0.0201, 0.0151, 0.7688, 0.0000, 0.0302])
tensor([0.3105])
tensor(-1.)
22/500


2301it [09:57,  3.85it/s]                        



loss: 1.3115021536747613
Policy Loss 0.1822824403643608
Value Loss 0.764654832581679
Examples:
tensor([-0.0419,  0.0780,  0.0519,  0.0721,  0.6805,  0.1909,  0.0928])
tensor([0.0000, 0.0251, 0.0151, 0.0050, 0.9045, 0.0352, 0.0151])
tensor([-0.3197])
tensor(0.)
23/500


2434it [09:56,  4.08it/s]                       



loss: 1.3646718913858589
Policy Loss 0.17665522477843545
Value Loss 0.8347062170505524
Examples:
tensor([-0.0209,  0.4869,  0.0516,  0.0502,  0.1807,  0.2945,  0.0329])
tensor([0.0000, 0.5528, 0.0000, 0.0000, 0.0955, 0.2010, 0.1508])
tensor([0.4779])
tensor(1.)
24/500


2451it [09:39,  4.23it/s]                       



loss: 1.325039615007964
Policy Loss 0.19012083451856265
Value Loss 0.754677111452276
Examples:
tensor([0.1300, 0.4575, 0.0958, 0.1253, 0.1314, 0.0492, 0.0026])
tensor([0.0201, 0.1558, 0.0251, 0.7337, 0.0302, 0.0151, 0.0201])
tensor([0.4081])
tensor(1.)
25/500


1978it [11:18,  2.92it/s]                        



loss: 1.2907492203208117
Policy Loss 0.18285363396772972
Value Loss 0.7421883184176225
Examples:
tensor([-0.0372,  0.3064,  0.0140,  0.1143,  0.1760,  0.3611, -0.0566])
tensor([0.0000, 0.1508, 0.0503, 0.1156, 0.0653, 0.6181, 0.0000])
tensor([0.3264])
tensor(1.)
26/500


1937it [11:26,  2.82it/s]                        



loss: 1.119222691999032
Policy Loss 0.1570100113749504
Value Loss 0.6481926578741807
Examples:
tensor([0.0046, 0.0996, 0.1838, 0.0977, 0.1667, 0.3873, 0.1174])
tensor([0.0101, 0.0302, 0.1055, 0.0000, 0.0804, 0.7538, 0.0201])
tensor([0.2456])
tensor(1.)
New best loss: 1.119222691999032
27/500


1867it [11:18,  2.75it/s]                        



loss: 1.1708153403467603
Policy Loss 0.16910755579118375
Value Loss 0.6634926729732089
Examples:
tensor([ 0.2802,  0.2451,  0.1932, -0.0738,  0.0544,  0.2269,  0.2343])
tensor([0.0653, 0.8744, 0.0402, 0.0000, 0.0000, 0.0201, 0.0000])
tensor([0.5642])
tensor(0.)
28/500


2149it [10:26,  3.43it/s]                        



loss: 1.2130307728052139
Policy Loss 0.15320396840572356
Value Loss 0.7534188675880432
Examples:
tensor([ 0.1798, -0.0802, -0.0907,  0.2225,  0.3586,  0.2230,  0.0727])
tensor([0.0452, 0.0000, 0.0000, 0.0804, 0.7739, 0.1005, 0.0000])
tensor([-0.6204])
tensor(-1.)
29/500


1470it [12:02,  2.04it/s]                        



loss: 1.1905238822102546
Policy Loss 0.16387186696132025
Value Loss 0.6989082813262939
Examples:
tensor([-0.0172,  0.7479, -0.0265,  0.1388, -0.0381,  0.1465, -0.0551])
tensor([0.1055, 0.5829, 0.0000, 0.1357, 0.0151, 0.1508, 0.0101])
tensor([-0.1295])
tensor(1.)
30/500


1586it [12:13,  2.16it/s]                        



loss: 1.1728496168707978
Policy Loss 0.16781522102397065
Value Loss 0.669403953798886
Examples:
tensor([ 0.0732, -0.0310, -0.0126, -0.0161,  0.3007,  0.4848,  0.1561])
tensor([0.0754, 0.0000, 0.0000, 0.0000, 0.3266, 0.5025, 0.0955])
tensor([-0.7823])
tensor(-1.)
31/500


2093it [10:38,  3.28it/s]                        



loss: 1.320592240691185
Policy Loss 0.18715127766132356
Value Loss 0.7591384077072143
Examples:
tensor([ 0.2092, -0.0137,  0.0550,  0.0765,  0.8406, -0.0727, -0.0230])
tensor([0.0754, 0.0050, 0.0050, 0.0251, 0.8844, 0.0000, 0.0050])
tensor([-0.3322])
tensor(-1.)
32/500


2044it [10:40,  3.19it/s]                        



loss: 1.1190571057108731
Policy Loss 0.15749534907249305
Value Loss 0.6465710584933941
Examples:
tensor([0.2725, 0.0926, 0.1109, 0.2184, 0.0073, 0.1268, 0.1798])
tensor([0.2161, 0.0804, 0.1859, 0.0653, 0.0000, 0.3920, 0.0603])
tensor([0.9369])
tensor(1.)
New best loss: 1.1190571057108731
33/500


1748it [11:51,  2.46it/s]                        



loss: 1.203269365642752
Policy Loss 0.19472714513540268
Value Loss 0.619087930236544
Examples:
tensor([ 0.2365,  0.0959,  0.0215,  0.4626,  0.2622, -0.0440, -0.0068])
tensor([0.3618, 0.1508, 0.0000, 0.2211, 0.1558, 0.0503, 0.0603])
tensor([-0.4468])
tensor(-1.)
34/500


2031it [10:48,  3.13it/s]                        



loss: 1.1730073005534134
Policy Loss 0.1404347290786413
Value Loss 0.7517031133174896
Examples:
tensor([ 0.2692,  0.0736,  0.0697,  0.0075, -0.0191,  0.2065,  0.2847])
tensor([0.6131, 0.0000, 0.0000, 0.0000, 0.0000, 0.0201, 0.3668])
tensor([0.0082])
tensor(-1.)
35/500


2257it [10:30,  3.58it/s]                        



loss: 1.2036208411057792
Policy Loss 0.16328682750463486
Value Loss 0.7137603585918745
Examples:
tensor([ 0.3317, -0.0130,  0.1054,  0.2311,  0.1253,  0.1003,  0.1811])
tensor([0.0402, 0.0000, 0.0000, 0.0151, 0.0101, 0.9246, 0.0101])
tensor([0.4711])
tensor(1.)
36/500


2051it [10:53,  3.14it/s]                        



loss: 1.1526533496379852
Policy Loss 0.16208893179893494
Value Loss 0.6663865542411804
Examples:
tensor([ 0.0096,  0.0070, -0.0380,  0.9015,  0.1293, -0.0021,  0.0084])
tensor([0.0050, 0.0000, 0.0000, 0.9899, 0.0000, 0.0000, 0.0050])
tensor([-0.2626])
tensor(-1.)
37/500


1578it [12:12,  2.16it/s]                        



loss: 1.1172877701705899
Policy Loss 0.14646124248874598
Value Loss 0.677904042704352
Examples:
tensor([0.0859, 0.5738, 0.0934, 0.0581, 0.0082, 0.1288, 0.0590])
tensor([0.0603, 0.7387, 0.0201, 0.0402, 0.0000, 0.0653, 0.0754])
tensor([-0.1146])
tensor(1.)
New best loss: 1.1172877701705899
38/500


1665it [11:50,  2.34it/s]                        



loss: 1.115606062380331
Policy Loss 0.13113712599234922
Value Loss 0.7221946844032833
Examples:
tensor([-0.0023,  0.0482,  0.7995,  0.0023,  0.0825,  0.0152,  0.0235])
tensor([0.0050, 0.0000, 0.7638, 0.0050, 0.1960, 0.0000, 0.0302])
tensor([-0.3650])
tensor(-1.)
New best loss: 1.115606062380331
39/500


1519it [12:22,  2.05it/s]                        



loss: 0.9909734395643075
Policy Loss 0.1277860186994076
Value Loss 0.6076153834660848
Examples:
tensor([ 0.0288,  0.1261,  0.3387, -0.0300,  0.2149,  0.2794,  0.1001])
tensor([0.0151, 0.1206, 0.1055, 0.0050, 0.5879, 0.1357, 0.0302])
tensor([-0.6233])
tensor(-1.)
New best loss: 0.9909734395643075
40/500


1532it [12:34,  2.03it/s]                        



loss: 1.022805093973875
Policy Loss 0.11630770539244016
Value Loss 0.6738819777965546
Examples:
tensor([-0.0050, -0.0223,  0.0074,  0.0011,  0.0528,  0.8547,  0.0392])
tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.9799, 0.0201])
tensor([0.4080])
tensor(-1.)
41/500


1278it [13:11,  1.61it/s]                        



loss: 0.9987262021750212
Policy Loss 0.11845455877482891
Value Loss 0.6433625258505344
Examples:
tensor([ 0.0423,  0.1430,  0.2434, -0.0020,  0.3398,  0.2478,  0.0085])
tensor([0.0553, 0.1859, 0.4020, 0.0000, 0.2010, 0.1508, 0.0050])
tensor([-0.6116])
tensor(-1.)
42/500


1432it [12:52,  1.85it/s]                        



loss: 0.8870581353704134
Policy Loss 0.09896484464406967
Value Loss 0.5901636014382045
Examples:
tensor([ 0.0052,  0.0149, -0.0326,  1.0229,  0.0075, -0.0040, -0.0047])
tensor([0.0050, 0.0050, 0.0050, 0.9698, 0.0050, 0.0050, 0.0050])
tensor([-0.5136])
tensor(-1.)
New best loss: 0.8870581353704134
43/500


1324it [13:23,  1.65it/s]                        



loss: 1.050375388514611
Policy Loss 0.11914460889754756
Value Loss 0.6929415618219683
Examples:
tensor([ 0.0148,  0.0273,  0.8974, -0.0142, -0.0580,  0.1444, -0.0107])
tensor([0.0000, 0.0050, 0.9598, 0.0000, 0.0000, 0.0302, 0.0050])
tensor([-0.2424])
tensor(-1.)
44/500


1326it [13:01,  1.70it/s]                        



loss: 0.898600530480185
Policy Loss 0.11608088569295022
Value Loss 0.5503578734013342
Examples:
tensor([ 0.0244, -0.0415,  0.0834,  0.0526,  0.1114,  0.8532,  0.0973])
tensor([0.0000, 0.0000, 0.2412, 0.0000, 0.0000, 0.6583, 0.1005])
tensor([0.9261])
tensor(1.)
45/500


1593it [12:17,  2.16it/s]                        



loss: 1.1018629801170579
Policy Loss 0.14315531813892826
Value Loss 0.6723970257002732
Examples:
tensor([ 0.1071, -0.0333,  0.1165,  0.0114,  0.7461, -0.0273, -0.0151])
tensor([0.0101, 0.0000, 0.3367, 0.0000, 0.6533, 0.0000, 0.0000])
tensor([0.8486])
tensor(1.)
46/500


2242it [10:30,  3.55it/s]                        



loss: 1.1346721950297556
Policy Loss 0.15136175199101368
Value Loss 0.6805869390567144
Examples:
tensor([-0.0022, -0.0110,  0.0266,  0.0581,  0.8620,  0.0638,  0.0710])
tensor([0.0000, 0.0050, 0.0101, 0.0000, 0.9095, 0.0101, 0.0653])
tensor([-0.0226])
tensor(-1.)
47/500


1792it [11:51,  2.52it/s]                        



loss: 1.040213616830962
Policy Loss 0.13713049462863378
Value Loss 0.6288221329450607
Examples:
tensor([ 0.1343,  0.0656,  0.0488,  0.3589, -0.0088,  0.3046,  0.0623])
tensor([0.3970, 0.0151, 0.0503, 0.1910, 0.0201, 0.2764, 0.0503])
tensor([-0.5181])
tensor(-1.)
48/500


1569it [12:43,  2.05it/s]                        



loss: 1.0436922435102791
Policy Loss 0.15076269774601378
Value Loss 0.5914041502722378
Examples:
tensor([ 0.3903, -0.0564, -0.0289,  0.0566, -0.0179,  0.6933,  0.0296])
tensor([0.6432, 0.0000, 0.0000, 0.0000, 0.0000, 0.3568, 0.0000])
tensor([0.4100])
tensor(-1.)
49/500


1555it [12:35,  2.06it/s]                        



loss: 0.8892689601614557
Policy Loss 0.12386423991671924
Value Loss 0.517676240411298
Examples:
tensor([ 0.4133, -0.0673, -0.0039,  0.0479,  0.2905,  0.0022,  0.2178])
tensor([0.1307, 0.0000, 0.0000, 0.0000, 0.5276, 0.0000, 0.3417])
tensor([-0.1984])
tensor(0.)
50/500


1616it [12:23,  2.17it/s]                        



loss: 0.9000845574613274
Policy Loss 0.11849660477761564
Value Loss 0.5445947431284806
Examples:
tensor([0.0689, 0.0566, 0.1211, 0.2284, 0.1082, 0.3384, 0.0437])
tensor([0.0101, 0.0352, 0.1106, 0.5829, 0.0251, 0.2312, 0.0050])
tensor([0.7290])
tensor(1.)
51/500


948it [14:38,  1.08it/s]                         



loss: 0.6323859481250538
Policy Loss 0.09864088805282817
Value Loss 0.3364632839665693
Examples:
tensor([-0.0183, -0.0580,  0.0622, -0.0360,  0.0439,  0.8832, -0.0308])
tensor([0.0000, 0.0000, 0.0101, 0.0000, 0.0000, 0.9849, 0.0050])
tensor([0.1192])
tensor(0.)
New best loss: 0.6323859481250538
52/500


1163it [14:02,  1.38it/s]                        



loss: 0.4985384178580716
Policy Loss 0.07749464537482709
Value Loss 0.26605448173359036
Examples:
tensor([-0.0182, -0.0283,  0.0422, -0.0211,  0.3297,  0.0043,  0.7116])
tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.2312, 0.0000, 0.7688])
tensor([-0.0457])
tensor(0.)
New best loss: 0.4985384178580716
53/500


1261it [13:14,  1.59it/s]                        



loss: 0.6721566298510879
Policy Loss 0.08124349848367274
Value Loss 0.4284261344000697
Examples:
tensor([ 0.0547, -0.0052,  0.7310,  0.0159,  0.0385, -0.0098,  0.1413])
tensor([0.0201, 0.0000, 0.8643, 0.0000, 0.0000, 0.0000, 0.1156])
tensor([-0.0694])
tensor(0.)
54/500


1495it [12:38,  1.97it/s]                        



loss: 0.967958648254474
Policy Loss 0.13187009568015734
Value Loss 0.572348361214002
Examples:
tensor([-0.0085,  0.9695,  0.0749, -0.0465,  0.0064, -0.0121, -0.0054])
tensor([0.0101, 0.9749, 0.0050, 0.0000, 0.0050, 0.0000, 0.0050])
tensor([0.0392])
tensor(1.)
55/500


972it [14:29,  1.12it/s]                         



loss: 0.6329771740471615
Policy Loss 0.08800053377361859
Value Loss 0.36897557272630577
Examples:
tensor([ 0.2367,  0.1233, -0.0079, -0.0187,  0.2978,  0.2939,  0.0200])
tensor([0.0754, 0.0653, 0.0000, 0.0000, 0.8040, 0.0402, 0.0151])
tensor([0.6579])
tensor(1.)
56/500


1024it [14:19,  1.19it/s]                        



loss: 0.5997443135608644
Policy Loss 0.08808735254056313
Value Loss 0.3354822559391751
Examples:
tensor([0.1832, 0.1403, 0.4587, 0.0807, 0.0354, 0.0808, 0.0849])
tensor([0.0653, 0.2613, 0.4221, 0.1709, 0.0503, 0.0151, 0.0151])
tensor([-0.9122])
tensor(-1.)
57/500


895it [15:03,  1.01s/it]                         



loss: 0.5832178074334349
Policy Loss 0.07077312756861959
Value Loss 0.3708984247275761
Examples:
tensor([ 0.0179,  0.8687,  0.0017,  0.0188, -0.0114,  0.0471, -0.0471])
tensor([0.0050, 0.9698, 0.0151, 0.0000, 0.0050, 0.0050, 0.0000])
tensor([0.3098])
tensor(0.)
58/500


1150it [13:54,  1.38it/s]                        



loss: 0.6382888070110119
Policy Loss 0.08144874080564037
Value Loss 0.39394258459409076
Examples:
tensor([0.0244, 0.0363, 0.2887, 0.0032, 0.4721, 0.1304, 0.0723])
tensor([0.0000, 0.0201, 0.1859, 0.0000, 0.2513, 0.4874, 0.0553])
tensor([-0.3562])
tensor(-1.)
59/500


786it [14:33,  1.11s/it]                         



loss: 0.5336680575140885
Policy Loss 0.07497134921806199
Value Loss 0.30875400985990253
Examples:
tensor([ 0.0113,  0.0612, -0.0090, -0.0332, -0.0286,  0.0382,  0.9974])
tensor([0., 0., 0., 0., 0., 0., 1.])
tensor([0.1047])
tensor(0.)
60/500


748it [32:21,  2.60s/it]                         



loss: 0.5011533130374219
Policy Loss 0.06515524329410659
Value Loss 0.3056875831551022
Examples:
tensor([ 1.2734e-01, -2.1984e-02, -5.2184e-03, -1.4453e-02,  9.1167e-01,
        -1.7269e-04, -3.6967e-02])
tensor([0.0151, 0.0000, 0.0000, 0.0000, 0.9849, 0.0000, 0.0000])
tensor([0.0921])
tensor(0.)
61/500


 52%|█████▏    | 66/128 [07:37<02:13,  2.15s/it]