In [23]:
%load_ext autoreload
%autoreload 2

import torch
from alpha_connect import AlphaZeroModelConnect4, Trainer
import os

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [28]:
device = torch.device("mps")

args = {
    "batch_size": 64,
    "numIters": 500,  # Total number of training iterations
    "num_simulations": 200,  # Total number of MCTS simulations to run when deciding on a move to play
    "numEps": 10,  # Number of full games (episodes) to run during each iteration
    "numItersForTrainExamplesHistory": 20,
    "epochs": 2,  # Number of epochs of training per iteration
    "checkpoint_path": "../data/latest.pth",  # location to save latest set of weights
}

if os.path.exists(args["checkpoint_path"]):
    model = AlphaZeroModelConnect4()
    model.load_state_dict(torch.load(args["checkpoint_path"]))
    print("Loaded model from checkpoint")
else:
    model = AlphaZeroModelConnect4()
model.to(device)

trainer = Trainer(model, args)
trainer.learn()

Loaded model from checkpoint
1/500


100%|██████████| 10/10 [07:52<00:00, 47.26s/it]


Winners:  {0: 8, 1: 2}

Policy Loss 0.030883225612342358
Value Loss 0.9059318006038666
Examples:
tensor([0.0964, 0.1547, 0.1379, 0.1343, 0.1063, 0.1069, 0.0967])
tensor([0.1263, 0.2245, 0.1582, 0.1232, 0.1238, 0.1220, 0.1220])
tensor([0.0183])
tensor(1.)

Policy Loss 0.030240002553910017
Value Loss 0.8180217146873474
Examples:
tensor([0.1102, 0.1919, 0.1523, 0.1731, 0.1169, 0.1354, 0.1093])
tensor([0.2572, 0.1215, 0.1284, 0.1271, 0.1215, 0.1215, 0.1227])
tensor([0.0485])
tensor(1.)
2/500


100%|██████████| 10/10 [08:25<00:00, 50.54s/it]


Winners:  {0: 6, 1: 4}

Policy Loss 0.02474882733076811
Value Loss 0.9298300743103027
Examples:
tensor([0.1615, 0.1382, 0.1531, 0.1576, 0.1474, 0.1427, 0.1308])
tensor([0.1382, 0.1731, 0.1251, 0.1289, 0.1382, 0.1497, 0.1468])
tensor([0.0231])
tensor(-1.)

Policy Loss 0.023783096112310886
Value Loss 0.8435750901699066
Examples:
tensor([0.1146, 0.0837, 0.1307, 0.1073, 0.1620, 0.1220, 0.1019])
tensor([0.1237, 0.1225, 0.1189, 0.1213, 0.2686, 0.1213, 0.1237])
tensor([-0.1389])
tensor(-1.)
3/500


100%|██████████| 10/10 [10:41<00:00, 64.19s/it]


Winners:  {1: 5, 0: 5}

Policy Loss 0.023336670051018398
Value Loss 1.1340914169947307
Examples:
tensor([0.1667, 0.1603, 0.1871, 0.1737, 0.1563, 0.1364, 0.1381])
tensor([0.1318, 0.2036, 0.1399, 0.1385, 0.1253, 0.1324, 0.1285])
tensor([-0.0755])
tensor(1.)

Policy Loss 0.022019571935137112
Value Loss 1.0327300528685253
Examples:
tensor([0.1397, 0.1043, 0.1530, 0.1285, 0.1132, 0.1111, 0.1081])
tensor([0.1186, 0.1186, 0.1186, 0.1186, 0.2802, 0.1222, 0.1234])
tensor([0.0318])
tensor(-1.)
4/500


100%|██████████| 10/10 [08:37<00:00, 51.77s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.018670220859348774
Value Loss 0.9999293386936188
Examples:
tensor([0.1121, 0.1698, 0.1156, 0.1485, 0.1326, 0.1519, 0.1249])
tensor([0.1475, 0.1460, 0.1424, 0.1475, 0.1368, 0.1389, 0.1410])
tensor([0.0939])
tensor(1.)

Policy Loss 0.018605255521833897
Value Loss 0.9705737680196762
Examples:
tensor([0.1521, 0.1787, 0.1914, 0.1385, 0.1822, 0.1338, 0.1601])
tensor([0.2790, 0.1193, 0.1199, 0.1193, 0.1193, 0.1199, 0.1235])
tensor([0.0531])
tensor(1.)
5/500


100%|██████████| 10/10 [08:04<00:00, 48.48s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.014568011276423931
Value Loss 1.0287421941757202
Examples:
tensor([0.1155, 0.1692, 0.0990, 0.1913, 0.1286, 0.1386, 0.1161])
tensor([0.1421, 0.1319, 0.1393, 0.1400, 0.1660, 0.1407, 0.1400])
tensor([0.0494])
tensor(-1.)

Policy Loss 0.013831439195200801
Value Loss 0.98476542532444
Examples:
tensor([0.1585, 0.1209, 0.1654, 0.1580, 0.1459, 0.1375, 0.1292])
tensor([0.1253, 0.1253, 0.2377, 0.1241, 0.1358, 0.1253, 0.1266])
tensor([0.1518])
tensor(1.)
6/500


100%|██████████| 10/10 [09:30<00:00, 57.06s/it]


Winners:  {1: 8, 0: 2}

Policy Loss 0.022730952749649685
Value Loss 0.9989789724349976
Examples:
tensor([0.1271, 0.1629, 0.1362, 0.1369, 0.1378, 0.1504, 0.1223])
tensor([0.2873, 0.1192, 0.1198, 0.1180, 0.1186, 0.1186, 0.1186])
tensor([0.1860])
tensor(1.)

Policy Loss 0.021902984008193016
Value Loss 0.9868660569190979
Examples:
tensor([0.1652, 0.1348, 0.1863, 0.1327, 0.1633, 0.1153, 0.1496])
tensor([0.1452, 0.1526, 0.1367, 0.1496, 0.1423, 0.1340, 0.1395])
tensor([0.0010])
tensor(1.)
7/500


100%|██████████| 10/10 [09:05<00:00, 54.52s/it]


Winners:  {0: 4, 1: 6}

Policy Loss 0.021782012035449345
Value Loss 0.9131079316139221
Examples:
tensor([0.0957, 0.1355, 0.0793, 0.1217, 0.1395, 0.1558, 0.0903])
tensor([0.3188, 0.1362, 0.0000, 0.1362, 0.1362, 0.1362, 0.1362])
tensor([0.1298])
tensor(-1.)

Policy Loss 0.020361411074797314
Value Loss 0.8696831464767456
Examples:
tensor([0.1216, 0.1577, 0.1636, 0.1737, 0.1234, 0.1206, 0.1177])
tensor([0.1288, 0.1381, 0.1980, 0.1381, 0.1354, 0.1314, 0.1301])
tensor([0.0376])
tensor(-1.)
8/500


100%|██████████| 10/10 [06:46<00:00, 40.69s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.010864319279789925
Value Loss 0.9110168218612671
Examples:
tensor([0.2072, 0.1431, 0.1782, 0.1918, 0.1885, 0.1861, 0.1391])
tensor([0.1268, 0.1374, 0.1402, 0.2112, 0.1281, 0.1268, 0.1294])
tensor([0.0320])
tensor(1.)

Policy Loss 0.009816752863116562
Value Loss 0.9119394570589066
Examples:
tensor([0.1010, 0.1410, 0.1539, 0.1457, 0.1499, 0.1074, 0.1314])
tensor([0.1276, 0.1410, 0.1355, 0.1961, 0.1315, 0.1341, 0.1341])
tensor([-0.0013])
tensor(1.)
9/500


100%|██████████| 10/10 [08:20<00:00, 50.03s/it]


Winners:  {1: 3, 0: 7}

Policy Loss 0.01750681595876813
Value Loss 0.8884022533893585
Examples:
tensor([0.1527, 0.1607, 0.1604, 0.1834, 0.1232, 0.1652, 0.1334])
tensor([0.1299, 0.1579, 0.1379, 0.1548, 0.1450, 0.1379, 0.1366])
tensor([0.0397])
tensor(-1.)

Policy Loss 0.016222984297201037
Value Loss 0.9279378801584244
Examples:
tensor([0.1312, 0.1675, 0.0943, 0.1618, 0.1683, 0.1095, 0.1192])
tensor([0.1768, 0.1768, 0.0000, 0.1751, 0.1768, 0.2945, 0.0000])
tensor([0.0272])
tensor(-1.)
10/500


100%|██████████| 10/10 [08:23<00:00, 50.37s/it]


Winners:  {1: 9, 0: 1}

Policy Loss 0.026828451547771692
Value Loss 0.7885900139808655
Examples:
tensor([0.2528, 0.1472, 0.2236, 0.2017, 0.1766, 0.1879, 0.1365])
tensor([0.1245, 0.1390, 0.2032, 0.1536, 0.1270, 0.1257, 0.1270])
tensor([-0.3490])
tensor(-1.)

Policy Loss 0.021615947131067514
Value Loss 0.7240547835826874
Examples:
tensor([0.1274, 0.1045, 0.1592, 0.1776, 0.1577, 0.1152, 0.1352])
tensor([0.1313, 0.1353, 0.1465, 0.1436, 0.1588, 0.1394, 0.1451])
tensor([-0.2280])
tensor(-1.)
11/500


100%|██████████| 10/10 [10:41<00:00, 64.19s/it]


Winners:  {1: 8, 0: 2}

Policy Loss 0.023443988834818203
Value Loss 0.9220427672068278
Examples:
tensor([0.1583, 0.1429, 0.1900, 0.1821, 0.1762, 0.1617, 0.1450])
tensor([0.1179, 0.1179, 0.1191, 0.2885, 0.1191, 0.1197, 0.1179])
tensor([-0.0247])
tensor(1.)

Policy Loss 0.021418977839251358
Value Loss 0.8624982337156931
Examples:
tensor([0.1073, 0.1505, 0.1549, 0.1380, 0.1744, 0.1213, 0.1492])
tensor([0.1256, 0.1764, 0.1320, 0.1459, 0.1533, 0.1388, 0.1281])
tensor([0.0629])
tensor(1.)
12/500


100%|██████████| 10/10 [10:14<00:00, 61.50s/it]


Winners:  {0: 4, 1: 6}

Policy Loss 0.0230418195327123
Value Loss 1.076911171277364
Examples:
tensor([0.0619, 0.1674, 0.1169, 0.1401, 0.1117, 0.1422, 0.1255])
tensor([0.2018, 0.2132, 0.0000, 0.2069, 0.0000, 0.1844, 0.1938])
tensor([-0.8209])
tensor(-1.)

Policy Loss 0.022041129569212597
Value Loss 0.9982331792513529
Examples:
tensor([0.0870, 0.1213, 0.1552, 0.1874, 0.1388, 0.1152, 0.1134])
tensor([0.1300, 0.1300, 0.1320, 0.1307, 0.1320, 0.2133, 0.1320])
tensor([0.0089])
tensor(-1.)
13/500


100%|██████████| 10/10 [07:41<00:00, 46.19s/it]


Winners:  {0: 4, 1: 6}

Policy Loss 0.016875077039003372
Value Loss 0.9536139667034149
Examples:
tensor([0.1209, 0.1517, 0.1203, 0.2216, 0.1457, 0.1699, 0.1366])
tensor([0.1313, 0.1313, 0.1340, 0.1381, 0.1999, 0.1340, 0.1313])
tensor([0.0017])
tensor(-1.)

Policy Loss 0.015158786438405514
Value Loss 0.879167452454567
Examples:
tensor([0.1059, 0.1630, 0.1711, 0.1444, 0.1876, 0.1630, 0.1541])
tensor([0.1172, 0.1172, 0.1172, 0.1172, 0.2970, 0.1172, 0.1172])
tensor([-0.4553])
tensor(-1.)
14/500


100%|██████████| 10/10 [08:46<00:00, 52.61s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.01916368429859479
Value Loss 1.0276254018147786
Examples:
tensor([0.1203, 0.1258, 0.1326, 0.1074, 0.1642, 0.1519, 0.1086])
tensor([0.1281, 0.1373, 0.2133, 0.1333, 0.1306, 0.1281, 0.1293])
tensor([0.0225])
tensor(-1.)

Policy Loss 0.017620950782050688
Value Loss 0.978619376818339
Examples:
tensor([0.0927, 0.1331, 0.1170, 0.1210, 0.1167, 0.1152, 0.1713])
tensor([0.1173, 0.1179, 0.1173, 0.1173, 0.2958, 0.1173, 0.1173])
tensor([0.3586])
tensor(1.)
15/500


100%|██████████| 10/10 [08:23<00:00, 50.36s/it]


Winners:  {0: 8, 1: 2}

Policy Loss 0.015640562400221825
Value Loss 0.9387343327204386
Examples:
tensor([0.1734, 0.1263, 0.1384, 0.1699, 0.1701, 0.1686, 0.1273])
tensor([0.1235, 0.1235, 0.2562, 0.1247, 0.1247, 0.1235, 0.1241])
tensor([-0.0321])
tensor(-1.)

Policy Loss 0.01565678541858991
Value Loss 0.9169447521368662
Examples:
tensor([0.1659, 0.1480, 0.1581, 0.1232, 0.1527, 0.1563, 0.1159])
tensor([0.1330, 0.1253, 0.1377, 0.2282, 0.1253, 0.1253, 0.1253])
tensor([0.4455])
tensor(1.)
16/500


100%|██████████| 10/10 [07:56<00:00, 47.68s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.015631365589797497
Value Loss 0.899210512638092
Examples:
tensor([0.1357, 0.1584, 0.1577, 0.1554, 0.1495, 0.1613, 0.1305])
tensor([0.1587, 0.1267, 0.1254, 0.1267, 0.1494, 0.1745, 0.1386])
tensor([0.1245])
tensor(1.)

Policy Loss 0.015593914780765772
Value Loss 0.9086865484714508
Examples:
tensor([0.1008, 0.1481, 0.1470, 0.1748, 0.1458, 0.1346, 0.1518])
tensor([0.1277, 0.1277, 0.1303, 0.1303, 0.1370, 0.2192, 0.1277])
tensor([0.0031])
tensor(1.)
17/500


100%|██████████| 10/10 [07:59<00:00, 47.97s/it]


Winners:  {0: 6, 1: 4}

Policy Loss 0.01592349261045456
Value Loss 0.9594725966453552
Examples:
tensor([0.0972, 0.1209, 0.1444, 0.1324, 0.1360, 0.1151, 0.1496])
tensor([0.1424, 0.1438, 0.1467, 0.1467, 0.1438, 0.1396, 0.1368])
tensor([0.1152])
tensor(-1.)

Policy Loss 0.01635882258415222
Value Loss 0.9389484524726868
Examples:
tensor([0.1034, 0.1026, 0.1473, 0.1342, 0.1558, 0.0969, 0.1217])
tensor([0.1243, 0.1243, 0.1353, 0.2345, 0.1306, 0.1261, 0.1249])
tensor([-0.1446])
tensor(-1.)
18/500


100%|██████████| 10/10 [07:16<00:00, 43.68s/it]


Winners:  {0: 4, 1: 6}

Policy Loss 0.010671583469957113
Value Loss 0.7672467231750488
Examples:
tensor([0.1359, 0.1121, 0.1334, 0.1475, 0.1462, 0.1154, 0.1054])
tensor([0.1320, 0.1367, 0.1281, 0.2242, 0.1249, 0.1255, 0.1287])
tensor([0.0267])
tensor(1.)

Policy Loss 0.013436815002933145
Value Loss 0.6663873046636581
Examples:
tensor([0.1519, 0.1347, 0.1521, 0.2032, 0.1874, 0.1541, 0.1458])
tensor([0.1364, 0.1324, 0.1463, 0.1601, 0.1364, 0.1601, 0.1285])
tensor([0.7293])
tensor(1.)
19/500


100%|██████████| 10/10 [07:49<00:00, 46.96s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.016596768982708454
Value Loss 1.2257688641548157
Examples:
tensor([0.0959, 0.1018, 0.1019, 0.1664, 0.1244, 0.1526, 0.1405])
tensor([0.1321, 0.1505, 0.1696, 0.1527, 0.1431, 0.1257, 0.1263])
tensor([0.5885])
tensor(-1.)

Policy Loss 0.014842001022771
Value Loss 1.0977506041526794
Examples:
tensor([0.1332, 0.1219, 0.1255, 0.1785, 0.1854, 0.1556, 0.1119])
tensor([0.1329, 0.1329, 0.1356, 0.1924, 0.1397, 0.1411, 0.1252])
tensor([-0.0693])
tensor(-1.)
20/500


100%|██████████| 10/10 [08:56<00:00, 53.63s/it]


Winners:  {1: 1, 0: 9}

Policy Loss 0.014404354151338339
Value Loss 0.978919506072998
Examples:
tensor([0.1499, 0.1379, 0.1131, 0.1226, 0.1611, 0.1373, 0.1154])
tensor([0.1237, 0.1262, 0.1313, 0.2441, 0.1249, 0.1237, 0.1262])
tensor([-0.0600])
tensor(-1.)

Policy Loss 0.014403684996068478
Value Loss 0.8688356876373291
Examples:
tensor([0.1405, 0.1564, 0.1711, 0.1602, 0.1449, 0.1514, 0.1401])
tensor([0.1229, 0.1229, 0.1229, 0.1217, 0.1217, 0.2629, 0.1248])
tensor([0.1437])
tensor(-1.)
21/500


100%|██████████| 10/10 [10:40<00:00, 64.06s/it]


Winners:  {1: 4, 0: 6}

Policy Loss 0.026919247582554817
Value Loss 1.0258628328641255
Examples:
tensor([0.1284, 0.1026, 0.1314, 0.1360, 0.1412, 0.1234, 0.1326])
tensor([0.1278, 0.1311, 0.1666, 0.1936, 0.1278, 0.1259, 0.1272])
tensor([-0.0571])
tensor(1.)

Policy Loss 0.02613732311874628
Value Loss 0.9401659170786539
Examples:
tensor([0.1737, 0.1128, 0.1926, 0.1752, 0.1505, 0.1192, 0.1572])
tensor([0.1241, 0.1253, 0.2562, 0.1241, 0.1228, 0.1228, 0.1247])
tensor([-0.4665])
tensor(-1.)
22/500


100%|██████████| 10/10 [06:57<00:00, 41.70s/it]


Winners:  {0: 6, 1: 4}

Policy Loss 0.018739034421741962
Value Loss 0.8718646764755249
Examples:
tensor([0.0998, 0.1372, 0.1263, 0.1281, 0.1689, 0.1266, 0.1224])
tensor([0.1189, 0.1189, 0.1213, 0.2755, 0.1226, 0.1213, 0.1213])
tensor([0.0765])
tensor(1.)

Policy Loss 0.018978659063577652
Value Loss 0.7979018539190292
Examples:
tensor([0.0655, 0.0988, 0.1003, 0.1164, 0.1235, 0.0865, 0.2123])
tensor([0.1241, 0.1241, 0.1254, 0.2354, 0.1241, 0.1435, 0.1235])
tensor([0.7920])
tensor(1.)
23/500


100%|██████████| 10/10 [10:12<00:00, 61.30s/it]


Winners:  {1: 5, 0: 5}

Policy Loss 0.0231890423844258
Value Loss 0.9831046859423319
Examples:
tensor([0.1027, 0.1580, 0.0768, 0.1701, 0.1466, 0.1533, 0.1383])
tensor([0.1365, 0.1365, 0.1421, 0.1539, 0.1338, 0.1338, 0.1634])
tensor([0.5965])
tensor(1.)

Policy Loss 0.021974981452027958
Value Loss 0.9059933423995972
Examples:
tensor([0.0831, 0.1223, 0.1495, 0.1471, 0.1061, 0.1286, 0.1364])
tensor([0.1479, 0.1479, 0.1571, 0.1407, 0.1479, 0.1286, 0.1299])
tensor([0.2373])
tensor(-1.)
24/500


100%|██████████| 10/10 [09:40<00:00, 58.07s/it]


Winners:  {0: 6, 1: 4}

Policy Loss 0.023852537696560223
Value Loss 0.9365126887957255
Examples:
tensor([0.1354, 0.1417, 0.1518, 0.1490, 0.1416, 0.1598, 0.1517])
tensor([0.1196, 0.1196, 0.1196, 0.2826, 0.1196, 0.1196, 0.1196])
tensor([0.0330])
tensor(-1.)

Policy Loss 0.023014035386343796
Value Loss 0.8535266319910685
Examples:
tensor([0.1182, 0.1441, 0.1518, 0.1197, 0.1727, 0.1437, 0.1118])
tensor([0.1294, 0.1333, 0.1333, 0.1346, 0.1268, 0.1294, 0.2133])
tensor([0.0873])
tensor(1.)
25/500


100%|██████████| 10/10 [07:55<00:00, 47.53s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.015941213350743055
Value Loss 1.0214070081710815
Examples:
tensor([0.1294, 0.1415, 0.1438, 0.1618, 0.1459, 0.1578, 0.1339])
tensor([0.1229, 0.1229, 0.1217, 0.2550, 0.1318, 0.1229, 0.1229])
tensor([-0.0079])
tensor(1.)

Policy Loss 0.017880474450066686
Value Loss 0.9415608048439026
Examples:
tensor([0.1526, 0.1233, 0.1585, 0.1490, 0.1486, 0.1684, 0.1388])
tensor([0.1238, 0.1238, 0.1904, 0.1226, 0.1251, 0.1238, 0.1904])
tensor([0.0105])
tensor(1.)
26/500


100%|██████████| 10/10 [08:12<00:00, 49.25s/it]


Winners:  {0: 6, 1: 4}

Policy Loss 0.017121328972280025
Value Loss 0.990063488483429
Examples:
tensor([0.1113, 0.1224, 0.1305, 0.1203, 0.1503, 0.1015, 0.1587])
tensor([0.1377, 0.1350, 0.1364, 0.1337, 0.1448, 0.1391, 0.1733])
tensor([0.0726])
tensor(1.)

Policy Loss 0.01583871222101152
Value Loss 0.9201275706291199
Examples:
tensor([0.1523, 0.1389, 0.1567, 0.1233, 0.1291, 0.1426, 0.1642])
tensor([0.1318, 0.1298, 0.1358, 0.1338, 0.2046, 0.1318, 0.1324])
tensor([-0.2263])
tensor(-1.)
27/500


100%|██████████| 10/10 [15:09<00:00, 90.91s/it] 


Winners:  {0: 6, 1: 4}

Policy Loss 0.01689339056611061
Value Loss 1.0550637543201447
Examples:
tensor([0.1779, 0.1406, 0.0430, 0.1214, 0.0774, 0.1394, 0.1484])
tensor([0.1571, 0.1571, 0.2143, 0.1579, 0.0000, 0.1564, 0.1571])
tensor([0.0749])
tensor(1.)

Policy Loss 0.015984603902325034
Value Loss 1.0151967108249664
Examples:
tensor([0.1254, 0.0722, 0.1235, 0.1239, 0.1380, 0.1192, 0.1372])
tensor([0.1410, 0.1295, 0.1775, 0.1302, 0.1460, 0.1341, 0.1417])
tensor([0.0574])
tensor(1.)
28/500


100%|██████████| 10/10 [35:16<00:00, 211.67s/it] 


Winners:  {1: 5, 0: 5}

Policy Loss 0.020363576089342434
Value Loss 0.9487603306770325
Examples:
tensor([0.1068, 0.1459, 0.1272, 0.1778, 0.1519, 0.1292, 0.1205])
tensor([0.1297, 0.1363, 0.1336, 0.2075, 0.1310, 0.1323, 0.1297])
tensor([-0.0458])
tensor(-1.)

Policy Loss 0.01883842299381892
Value Loss 0.9022840162118276
Examples:
tensor([0.0849, 0.1201, 0.1412, 0.1810, 0.1529, 0.1551, 0.1356])
tensor([0.1398, 0.1405, 0.1350, 0.1363, 0.1751, 0.1370, 0.1363])
tensor([0.2468])
tensor(1.)
29/500


100%|██████████| 10/10 [08:26<00:00, 50.61s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.018518733481566112
Value Loss 0.959377388159434
Examples:
tensor([0.1565, 0.1318, 0.1360, 0.1557, 0.1535, 0.1850, 0.1709])
tensor([0.1260, 0.1260, 0.1406, 0.1311, 0.1995, 0.1508, 0.1260])
tensor([0.3503])
tensor(1.)

Policy Loss 0.016990965077032644
Value Loss 0.8929476241270701
Examples:
tensor([0.1046, 0.1472, 0.1247, 0.1644, 0.1673, 0.1164, 0.1089])
tensor([0.1289, 0.1276, 0.1315, 0.1829, 0.1688, 0.1315, 0.1289])
tensor([-0.1677])
tensor(-1.)
30/500


100%|██████████| 10/10 [09:17<00:00, 55.75s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.03206888027489185
Value Loss 1.0537614425023396
Examples:
tensor([0.1257, 0.1531, 0.1094, 0.1496, 0.1026, 0.1388, 0.1291])
tensor([0.1495, 0.1430, 0.1564, 0.1360, 0.1353, 0.1340, 0.1458])
tensor([-0.2917])
tensor(-1.)

Policy Loss 0.029543673619627953
Value Loss 0.9666480422019958
Examples:
tensor([0.1462, 0.1047, 0.1407, 0.1751, 0.1404, 0.1443, 0.1497])
tensor([0.1403, 0.1482, 0.1410, 0.1389, 0.1410, 0.1490, 0.1417])
tensor([0.0741])
tensor(1.)
31/500


100%|██████████| 10/10 [07:38<00:00, 45.84s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.012189189437776804
Value Loss 0.9314083755016327
Examples:
tensor([0.1073, 0.0895, 0.1446, 0.1284, 0.1580, 0.0908, 0.1158])
tensor([0.1207, 0.1207, 0.1207, 0.2685, 0.1207, 0.1207, 0.1281])
tensor([0.3732])
tensor(1.)

Policy Loss 0.012691873824223876
Value Loss 0.9084732085466385
Examples:
tensor([0.1546, 0.1342, 0.1922, 0.1778, 0.1779, 0.1602, 0.1953])
tensor([0.1212, 0.1249, 0.2618, 0.1236, 0.1224, 0.1236, 0.1224])
tensor([-0.1813])
tensor(-1.)
32/500


100%|██████████| 10/10 [07:35<00:00, 45.55s/it]


Winners:  {0: 8, 1: 2}

Policy Loss 0.013542763888835907
Value Loss 1.0003530085086823
Examples:
tensor([0.1287, 0.1913, 0.1492, 0.1388, 0.1245, 0.1195, 0.1272])
tensor([0.1429, 0.1267, 0.1280, 0.2131, 0.1359, 0.1267, 0.1267])
tensor([-0.2466])
tensor(1.)

Policy Loss 0.013595265103504062
Value Loss 0.8818352818489075
Examples:
tensor([0.1413, 0.1598, 0.1492, 0.1548, 0.1458, 0.1372, 0.1259])
tensor([0.2335, 0.1244, 0.1269, 0.1307, 0.1301, 0.1288, 0.1256])
tensor([0.5678])
tensor(1.)
33/500


100%|██████████| 10/10 [08:40<00:00, 52.05s/it]


Winners:  {0: 3, 1: 7}

Policy Loss 0.021676424890756607
Value Loss 0.8881764809290568
Examples:
tensor([0.1073, 0.1421, 0.1390, 0.1712, 0.1319, 0.1061, 0.1316])
tensor([0.1545, 0.0000, 0.1529, 0.3837, 0.0000, 0.1545, 0.1545])
tensor([-0.5915])
tensor(-1.)

Policy Loss 0.02096852163473765
Value Loss 0.8394418259461721
Examples:
tensor([0.1662, 0.1299, 0.1591, 0.1884, 0.1557, 0.1554, 0.1381])
tensor([0.1221, 0.1208, 0.1208, 0.1208, 0.1270, 0.1221, 0.2663])
tensor([-0.0589])
tensor(-1.)
34/500


100%|██████████| 10/10 [07:44<00:00, 46.43s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.01608161348849535
Value Loss 0.9089759886264801
Examples:
tensor([0.1957, 0.1319, 0.1678, 0.1848, 0.1716, 0.1776, 0.1153])
tensor([0.1207, 0.1213, 0.1207, 0.2686, 0.1237, 0.1237, 0.1213])
tensor([-0.5300])
tensor(-1.)

Policy Loss 0.01531051006168127
Value Loss 0.9027825891971588
Examples:
tensor([0.1013, 0.1275, 0.1350, 0.1405, 0.1565, 0.1255, 0.1006])
tensor([0.1411, 0.1397, 0.0000, 0.1624, 0.1607, 0.2446, 0.1514])
tensor([0.3743])
tensor(1.)
35/500


100%|██████████| 10/10 [08:07<00:00, 48.76s/it]


Winners:  {0: 3, 1: 7}

Policy Loss 0.017953981334964435
Value Loss 0.9543106357256571
Examples:
tensor([0.1395, 0.1263, 0.1391, 0.1661, 0.1608, 0.1713, 0.1119])
tensor([0.1219, 0.1207, 0.1207, 0.1219, 0.2686, 0.1244, 0.1219])
tensor([-0.1879])
tensor(-1.)

Policy Loss 0.017066235343615215
Value Loss 0.9250732163588206
Examples:
tensor([0.1466, 0.1344, 0.1400, 0.1602, 0.1579, 0.1573, 0.1146])
tensor([0.1376, 0.1356, 0.1316, 0.1329, 0.1322, 0.1953, 0.1349])
tensor([-0.3038])
tensor(-1.)
36/500


100%|██████████| 10/10 [09:14<00:00, 55.43s/it]


Winners:  {0: 4, 1: 6}

Policy Loss 0.010712587895492712
Value Loss 0.8812639315923055
Examples:
tensor([0.1616, 0.1651, 0.1497, 0.1539, 0.1447, 0.1172, 0.1441])
tensor([0.1872, 0.1373, 0.1373, 0.1359, 0.1332, 0.1346, 0.1346])
tensor([-0.0843])
tensor(1.)

Policy Loss 0.012044517478595177
Value Loss 0.7755753298600515
Examples:
tensor([0.1373, 0.1391, 0.2065, 0.1390, 0.1131, 0.1468, 0.1647])
tensor([0.1314, 0.1263, 0.2030, 0.1269, 0.1605, 0.1256, 0.1263])
tensor([-0.5634])
tensor(-1.)
37/500


100%|██████████| 10/10 [08:41<00:00, 52.11s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.028841173897186916
Value Loss 1.113930583000183
Examples:
tensor([0.1381, 0.1501, 0.1693, 0.1308, 0.1631, 0.1394, 0.1776])
tensor([0.1333, 0.1287, 0.1268, 0.1746, 0.1620, 0.1360, 0.1387])
tensor([0.1733])
tensor(-1.)

Policy Loss 0.027828877170880634
Value Loss 1.0122991899649303
Examples:
tensor([0.1178, 0.1213, 0.1255, 0.1216, 0.1541, 0.1208, 0.1720])
tensor([0.1172, 0.1172, 0.2970, 0.1172, 0.1172, 0.1172, 0.1172])
tensor([-0.2473])
tensor(1.)
38/500


100%|██████████| 10/10 [06:34<00:00, 39.47s/it]


Winners:  {0: 9, 1: 1}

Policy Loss 0.01659796992316842
Value Loss 1.089526653289795
Examples:
tensor([0.1465, 0.1338, 0.1371, 0.1254, 0.1352, 0.1281, 0.1570])
tensor([0.2595, 0.1214, 0.1214, 0.1251, 0.1226, 0.1238, 0.1263])
tensor([-0.0658])
tensor(1.)

Policy Loss 0.015061905840411782
Value Loss 1.0231941938400269
Examples:
tensor([0.2020, 0.1443, 0.1279, 0.1770, 0.1305, 0.1538, 0.1192])
tensor([0.1541, 0.1466, 0.1423, 0.1481, 0.1437, 0.1326, 0.1326])
tensor([0.0934])
tensor(-1.)
39/500


100%|██████████| 10/10 [07:31<00:00, 45.11s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.015191129874438047
Value Loss 1.0362102091312408
Examples:
tensor([0.1112, 0.1484, 0.1541, 0.1633, 0.1178, 0.0948, 0.1202])
tensor([0.1354, 0.1409, 0.1452, 0.1573, 0.1423, 0.1395, 0.1395])
tensor([0.2557])
tensor(1.)

Policy Loss 0.013515451224520802
Value Loss 0.9853736460208893
Examples:
tensor([0.1285, 0.1610, 0.1495, 0.1068, 0.1644, 0.1190, 0.1607])
tensor([0.1493, 0.1602, 0.1421, 0.1524, 0.1325, 0.1311, 0.1325])
tensor([-0.0519])
tensor(-1.)
40/500


100%|██████████| 10/10 [07:13<00:00, 43.37s/it]


Winners:  {0: 8, 1: 2}

Policy Loss 0.03037872724235058
Value Loss 0.9421059191226959
Examples:
tensor([0.1191, 0.1248, 0.1425, 0.1300, 0.1551, 0.0998, 0.1351])
tensor([0.1279, 0.1358, 0.1816, 0.1570, 0.1372, 0.1305, 0.1299])
tensor([-0.0429])
tensor(-1.)

Policy Loss 0.0286774430423975
Value Loss 0.9394147545099258
Examples:
tensor([0.1339, 0.0843, 0.1487, 0.1865, 0.1704, 0.1084, 0.1288])
tensor([0.1549, 0.1307, 0.1504, 0.1738, 0.1307, 0.1301, 0.1294])
tensor([-0.0355])
tensor(1.)
41/500


100%|██████████| 10/10 [06:08<00:00, 36.89s/it]


Winners:  {1: 4, 0: 6}

Policy Loss 0.01360856182873249
Value Loss 0.8632167875766754
Examples:
tensor([0.1445, 0.1340, 0.1825, 0.1382, 0.1537, 0.1664, 0.1332])
tensor([0.1217, 0.1205, 0.2537, 0.1217, 0.1379, 0.1229, 0.1217])
tensor([-0.0436])
tensor(-1.)

Policy Loss 0.01222547609359026
Value Loss 0.8089486956596375
Examples:
tensor([0.1528, 0.1438, 0.1591, 0.1399, 0.1379, 0.1928, 0.1486])
tensor([0.1383, 0.1277, 0.1264, 0.2191, 0.1277, 0.1343, 0.1264])
tensor([-0.0925])
tensor(-1.)
42/500


100%|██████████| 10/10 [07:55<00:00, 47.59s/it]


Winners:  {0: 6, 1: 4}

Policy Loss 0.019761209065715473
Value Loss 0.837634265422821
Examples:
tensor([0.1726, 0.1770, 0.1695, 0.1623, 0.1520, 0.1427, 0.1245])
tensor([0.1230, 0.1255, 0.2356, 0.1319, 0.1293, 0.1255, 0.1293])
tensor([-0.3840])
tensor(-1.)

Policy Loss 0.017943009734153748
Value Loss 0.8049171368281046
Examples:
tensor([0.1504, 0.1410, 0.1586, 0.1394, 0.1076, 0.1695, 0.1651])
tensor([0.1424, 0.1424, 0.1432, 0.1424, 0.1439, 0.1432, 0.1424])
tensor([0.4575])
tensor(-1.)
43/500


100%|██████████| 10/10 [07:26<00:00, 44.70s/it]


Winners:  {0: 6, 1: 4}

Policy Loss 0.030306384898722172
Value Loss 1.046740710735321
Examples:
tensor([0.1236, 0.1389, 0.1263, 0.1590, 0.1676, 0.1068, 0.1557])
tensor([0.1199, 0.1254, 0.1199, 0.1199, 0.2628, 0.1279, 0.1242])
tensor([-0.3374])
tensor(-1.)

Policy Loss 0.02717357501387596
Value Loss 0.9417741596698761
Examples:
tensor([0.1141, 0.1298, 0.1519, 0.1546, 0.1849, 0.1017, 0.1420])
tensor([0.1231, 0.1256, 0.1231, 0.2312, 0.1445, 0.1288, 0.1237])
tensor([-0.0827])
tensor(1.)
44/500


100%|██████████| 10/10 [05:47<00:00, 34.74s/it]


Winners:  {0: 6, 1: 4}

Policy Loss 0.011500379536300898
Value Loss 1.084331214427948
Examples:
tensor([0.1453, 0.1260, 0.1392, 0.1524, 0.1834, 0.1718, 0.1245])
tensor([0.1227, 0.1221, 0.1221, 0.2483, 0.1258, 0.1356, 0.1233])
tensor([-0.2117])
tensor(1.)

Policy Loss 0.012302256189286709
Value Loss 0.9877711236476898
Examples:
tensor([0.0838, 0.1206, 0.1027, 0.1748, 0.1214, 0.1170, 0.1005])
tensor([0.1201, 0.1201, 0.1213, 0.2594, 0.1341, 0.1225, 0.1225])
tensor([0.2008])
tensor(1.)
45/500


100%|██████████| 10/10 [07:38<00:00, 45.89s/it]


Winners:  {0: 6, 1: 4}

Policy Loss 0.01117284083738923
Value Loss 0.956975519657135
Examples:
tensor([0.1353, 0.1357, 0.1359, 0.1356, 0.1431, 0.1389, 0.1458])
tensor([0.1716, 0.1363, 0.1310, 0.1419, 0.1433, 0.1448, 0.1310])
tensor([-0.1640])
tensor(1.)

Policy Loss 0.010638898005709052
Value Loss 0.9598783552646637
Examples:
tensor([0.1315, 0.1339, 0.1729, 0.1327, 0.1615, 0.1195, 0.1070])
tensor([0.1347, 0.1307, 0.1459, 0.2092, 0.1282, 0.1256, 0.1256])
tensor([-0.0882])
tensor(1.)
46/500


100%|██████████| 10/10 [06:30<00:00, 39.07s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.009820085484534502
Value Loss 0.8817133009433746
Examples:
tensor([0.1458, 0.1204, 0.1624, 0.1457, 0.1542, 0.1413, 0.1254])
tensor([0.1242, 0.2355, 0.1267, 0.1372, 0.1280, 0.1242, 0.1242])
tensor([-0.0466])
tensor(1.)

Policy Loss 0.009560228558257222
Value Loss 0.8310995399951935
Examples:
tensor([0.1283, 0.1233, 0.1642, 0.1741, 0.1572, 0.1487, 0.1447])
tensor([0.1608, 0.1265, 0.1356, 0.1316, 0.1849, 0.1329, 0.1277])
tensor([0.0258])
tensor(1.)
47/500


100%|██████████| 10/10 [08:02<00:00, 48.22s/it]


Winners:  {1: 4, 0: 6}

Policy Loss 0.017824758154650528
Value Loss 0.8793663382530212
Examples:
tensor([0.1167, 0.1387, 0.1506, 0.1070, 0.1351, 0.0973, 0.1030])
tensor([0.1161, 0.3031, 0.1166, 0.1161, 0.1161, 0.1161, 0.1161])
tensor([0.0936])
tensor(1.)

Policy Loss 0.01546988527600964
Value Loss 0.8574433028697968
Examples:
tensor([0.1363, 0.1505, 0.1094, 0.1344, 0.1478, 0.1245, 0.1015])
tensor([0.1238, 0.1250, 0.1238, 0.2211, 0.1395, 0.1354, 0.1314])
tensor([0.4955])
tensor(1.)
48/500


100%|██████████| 10/10 [06:12<00:00, 37.24s/it]


Winners:  {1: 4, 0: 6}

Policy Loss 0.014651950914412737
Value Loss 1.0472458004951477
Examples:
tensor([0.0886, 0.1174, 0.1429, 0.1161, 0.1513, 0.1544, 0.0964])
tensor([0.1189, 0.1201, 0.1201, 0.1250, 0.1201, 0.2755, 0.1201])
tensor([0.5305])
tensor(-1.)

Policy Loss 0.013246627524495125
Value Loss 1.0194495022296906
Examples:
tensor([0.1266, 0.1434, 0.1628, 0.1559, 0.1040, 0.1357, 0.1411])
tensor([0.1196, 0.1196, 0.1196, 0.1196, 0.2826, 0.1196, 0.1196])
tensor([0.1170])
tensor(-1.)
49/500


100%|██████████| 10/10 [05:40<00:00, 34.01s/it]


Winners:  {0: 8, 1: 2}

Policy Loss 0.010805527679622173
Value Loss 1.0154695212841034
Examples:
tensor([0.1192, 0.1275, 0.1614, 0.1497, 0.1329, 0.1560, 0.1407])
tensor([0.1215, 0.1215, 0.2472, 0.1227, 0.1391, 0.1234, 0.1246])
tensor([0.0513])
tensor(1.)

Policy Loss 0.011822146596387029
Value Loss 0.978785514831543
Examples:
tensor([0.1623, 0.1298, 0.1839, 0.1476, 0.1720, 0.1244, 0.1576])
tensor([0.1288, 0.1301, 0.1301, 0.1262, 0.2232, 0.1327, 0.1288])
tensor([-0.0975])
tensor(-1.)
50/500


100%|██████████| 10/10 [07:20<00:00, 44.07s/it]


Winners:  {0: 4, 1: 6}

Policy Loss 0.0128605542704463
Value Loss 1.0502948760986328
Examples:
tensor([0.1377, 0.1405, 0.1634, 0.1592, 0.1456, 0.1223, 0.1386])
tensor([0.1421, 0.1393, 0.1352, 0.1684, 0.1379, 0.1393, 0.1379])
tensor([-0.1415])
tensor(1.)

Policy Loss 0.013281402178108692
Value Loss 0.9969940334558487
Examples:
tensor([0.0502, 0.1691, 0.1590, 0.1222, 0.1176, 0.0490, 0.0983])
tensor([0.1190, 0.1190, 0.1190, 0.1178, 0.2897, 0.1178, 0.1178])
tensor([0.1438])
tensor(1.)
51/500


100%|██████████| 10/10 [08:47<00:00, 52.74s/it]


Winners:  {1: 8, 0: 2}

Policy Loss 0.016659270351131756
Value Loss 0.9140463074048361
Examples:
tensor([0.1863, 0.1387, 0.1685, 0.1539, 0.1705, 0.1464, 0.1504])
tensor([0.1318, 0.1779, 0.1331, 0.1659, 0.1292, 0.1318, 0.1305])
tensor([0.0894])
tensor(1.)

Policy Loss 0.015784214561184246
Value Loss 0.8544890880584717
Examples:
tensor([0.1440, 0.1170, 0.1438, 0.1402, 0.1228, 0.1157, 0.1412])
tensor([0.1461, 0.1490, 0.1732, 0.1404, 0.1309, 0.1309, 0.1296])
tensor([0.0179])
tensor(1.)
52/500


100%|██████████| 10/10 [08:08<00:00, 48.88s/it]


Winners:  {0: 3, 1: 7}

Policy Loss 0.0151523199553291
Value Loss 0.9381280938784281
Examples:
tensor([0.1406, 0.2025, 0.1417, 0.1348, 0.1280, 0.1555, 0.0498])
tensor([0.1172, 0.1172, 0.1172, 0.1172, 0.1172, 0.2970, 0.1172])
tensor([0.3421])
tensor(-1.)

Policy Loss 0.013698994492491087
Value Loss 0.8828892111778259
Examples:
tensor([0.1041, 0.1455, 0.1271, 0.1559, 0.1366, 0.1300, 0.1241])
tensor([0.1258, 0.1309, 0.1390, 0.2292, 0.1246, 0.1246, 0.1258])
tensor([-0.2987])
tensor(-1.)
53/500


100%|██████████| 10/10 [08:23<00:00, 50.34s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.021429918085535366
Value Loss 0.7254366278648376
Examples:
tensor([0.1397, 0.1375, 0.1618, 0.1524, 0.1501, 0.1446, 0.1585])
tensor([0.1205, 0.1242, 0.2709, 0.1193, 0.1242, 0.1205, 0.1205])
tensor([0.0405])
tensor(1.)

Policy Loss 0.02059888963898023
Value Loss 0.6075472086668015
Examples:
tensor([0.1096, 0.1481, 0.1449, 0.1372, 0.1459, 0.1494, 0.1506])
tensor([0.1345, 0.1372, 0.1366, 0.1366, 0.1332, 0.1881, 0.1339])
tensor([-0.6837])
tensor(-1.)
54/500


100%|██████████| 10/10 [07:09<00:00, 43.00s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.015172350686043501
Value Loss 1.1642017364501953
Examples:
tensor([0.1578, 0.1355, 0.1191, 0.1281, 0.1358, 0.1676, 0.1201])
tensor([0.1230, 0.1230, 0.1237, 0.1224, 0.2618, 0.1237, 0.1224])
tensor([0.1608])
tensor(1.)

Policy Loss 0.013810209231451154
Value Loss 1.086488589644432
Examples:
tensor([0.1229, 0.1249, 0.1168, 0.1567, 0.1271, 0.1671, 0.1263])
tensor([0.1285, 0.1358, 0.1515, 0.1298, 0.1870, 0.1344, 0.1331])
tensor([0.2135])
tensor(-1.)
55/500


100%|██████████| 10/10 [06:22<00:00, 38.24s/it]


Winners:  {1: 5, 0: 5}

Policy Loss 0.010695811826735735
Value Loss 1.0377254486083984
Examples:
tensor([0.1249, 0.1229, 0.1144, 0.1357, 0.1501, 0.1690, 0.1384])
tensor([0.1342, 0.1239, 0.1227, 0.1239, 0.2169, 0.1336, 0.1447])
tensor([-0.0776])
tensor(-1.)

Policy Loss 0.011063451878726482
Value Loss 0.9849273562431335
Examples:
tensor([0.1539, 0.1049, 0.1554, 0.1369, 0.1606, 0.1649, 0.1623])
tensor([0.1660, 0.1387, 0.1255, 0.1660, 0.1280, 0.1255, 0.1502])
tensor([0.3525])
tensor(-1.)
56/500


100%|██████████| 10/10 [07:17<00:00, 43.79s/it]


Winners:  {0: 4, 1: 6}

Policy Loss 0.008584007155150175
Value Loss 0.9085433185100555
Examples:
tensor([0.1199, 0.1414, 0.1431, 0.1532, 0.1488, 0.1443, 0.1367])
tensor([0.1271, 0.1265, 0.1433, 0.1455, 0.1271, 0.2034, 0.1271])
tensor([0.2607])
tensor(-1.)

Policy Loss 0.00959428958594799
Value Loss 0.8823979794979095
Examples:
tensor([0.1207, 0.1332, 0.1431, 0.1592, 0.1497, 0.1485, 0.1453])
tensor([0.1278, 0.1284, 0.1297, 0.1265, 0.2294, 0.1278, 0.1304])
tensor([-0.1318])
tensor(1.)
57/500


100%|██████████| 10/10 [06:49<00:00, 40.98s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.011040130164474249
Value Loss 1.1831274032592773
Examples:
tensor([0.1238, 0.1490, 0.1295, 0.1508, 0.1499, 0.1601, 0.1492])
tensor([0.1248, 0.1224, 0.1293, 0.1255, 0.1286, 0.1242, 0.2452])
tensor([0.1922])
tensor(-1.)

Policy Loss 0.011757667642086744
Value Loss 1.0452914088964462
Examples:
tensor([0.1683, 0.1471, 0.1729, 0.1444, 0.1354, 0.1711, 0.1736])
tensor([0.1162, 0.1162, 0.1162, 0.1167, 0.3019, 0.1167, 0.1162])
tensor([0.1461])
tensor(1.)
58/500


100%|██████████| 10/10 [06:51<00:00, 41.19s/it]


Winners:  {0: 4, 1: 6}

Policy Loss 0.020899114664644003
Value Loss 0.9491718411445618
Examples:
tensor([0.1555, 0.1408, 0.1415, 0.1331, 0.1651, 0.1991, 0.1608])
tensor([0.1232, 0.1232, 0.1232, 0.1257, 0.2267, 0.1535, 0.1244])
tensor([-0.2127])
tensor(-1.)

Policy Loss 0.015837902203202248
Value Loss 0.8876817971467972
Examples:
tensor([0.1010, 0.1460, 0.1573, 0.1104, 0.1511, 0.1359, 0.0909])
tensor([0.1453, 0.1432, 0.1740, 0.0000, 0.1559, 0.1490, 0.2326])
tensor([0.3954])
tensor(1.)
59/500


100%|██████████| 10/10 [05:59<00:00, 35.98s/it]


Winners:  {1: 9, 0: 1}

Policy Loss 0.010053293313831091
Value Loss 1.1609041094779968
Examples:
tensor([0.1248, 0.1019, 0.1153, 0.1687, 0.1732, 0.1154, 0.1296])
tensor([0.1264, 0.1264, 0.1369, 0.1885, 0.1559, 0.1396, 0.1264])
tensor([0.0089])
tensor(1.)

Policy Loss 0.01039625913836062
Value Loss 1.0005896240472794
Examples:
tensor([0.1247, 0.1197, 0.1296, 0.1638, 0.1552, 0.1307, 0.1417])
tensor([0.1261, 0.1261, 0.1287, 0.1367, 0.1901, 0.1636, 0.1287])
tensor([0.0816])
tensor(-1.)
60/500


100%|██████████| 10/10 [07:21<00:00, 44.15s/it]


Winners:  {0: 6, 1: 4}

Policy Loss 0.01351615833118558
Value Loss 0.7255613207817078
Examples:
tensor([0.1339, 0.1524, 0.1318, 0.1766, 0.1691, 0.1471, 0.1412])
tensor([0.1246, 0.1259, 0.1259, 0.2485, 0.1246, 0.1259, 0.1246])
tensor([-0.2949])
tensor(-1.)

Policy Loss 0.012707999674603343
Value Loss 0.701055496931076
Examples:
tensor([0.1458, 0.1813, 0.1287, 0.1659, 0.1935, 0.1659, 0.1230])
tensor([0.1458, 0.1299, 0.1299, 0.1532, 0.1458, 0.1429, 0.1525])
tensor([-0.6331])
tensor(-1.)
61/500


100%|██████████| 10/10 [10:04<00:00, 60.48s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.018596429377794266
Value Loss 1.2321799596150715
Examples:
tensor([0.1359, 0.1191, 0.1502, 0.1727, 0.1668, 0.1461, 0.1407])
tensor([0.1296, 0.1283, 0.1476, 0.1498, 0.1270, 0.1886, 0.1290])
tensor([0.3848])
tensor(-1.)

Policy Loss 0.0185883737479647
Value Loss 1.105912019809087
Examples:
tensor([0.1200, 0.1242, 0.1448, 0.1455, 0.1604, 0.1329, 0.1112])
tensor([0.1243, 0.1255, 0.1255, 0.1255, 0.2334, 0.1401, 0.1255])
tensor([0.1988])
tensor(1.)
62/500


100%|██████████| 10/10 [07:24<00:00, 44.45s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.020071557722985744
Value Loss 0.987095057964325
Examples:
tensor([0.1126, 0.1033, 0.1333, 0.1654, 0.1436, 0.1383, 0.1202])
tensor([0.1257, 0.1245, 0.1257, 0.1296, 0.1335, 0.1598, 0.2012])
tensor([-0.2170])
tensor(-1.)

Policy Loss 0.018102980218827724
Value Loss 0.8969056308269501
Examples:
tensor([0.0484, 0.1421, 0.0864, 0.1406, 0.0851, 0.0591, 0.0941])
tensor([0.1673, 0.2084, 0.2074, 0.0000, 0.2084, 0.2084, 0.0000])
tensor([0.5347])
tensor(1.)
63/500


100%|██████████| 10/10 [08:09<00:00, 48.91s/it]


Winners:  {0: 3, 1: 7}

Policy Loss 0.018368962220847607
Value Loss 0.9671427011489868
Examples:
tensor([0.1187, 0.1448, 0.1624, 0.1530, 0.1391, 0.1114, 0.1220])
tensor([0.1328, 0.1943, 0.1328, 0.1454, 0.1342, 0.1276, 0.1328])
tensor([0.0288])
tensor(-1.)

Policy Loss 0.018084130094697077
Value Loss 0.8890043497085571
Examples:
tensor([0.1182, 0.1289, 0.1710, 0.1497, 0.1553, 0.1433, 0.1438])
tensor([0.1219, 0.1219, 0.1243, 0.1367, 0.2323, 0.1367, 0.1262])
tensor([-0.1463])
tensor(-1.)
64/500


100%|██████████| 10/10 [06:45<00:00, 40.59s/it]


Winners:  {1: 5, 0: 5}

Policy Loss 0.011092554312199354
Value Loss 0.770179808139801
Examples:
tensor([0.1192, 0.1126, 0.1393, 0.1519, 0.1310, 0.1503, 0.1325])
tensor([0.1263, 0.1424, 0.1756, 0.1275, 0.1756, 0.1263, 0.1263])
tensor([0.4890])
tensor(1.)

Policy Loss 0.011831952026113868
Value Loss 0.7572896629571915
Examples:
tensor([0.1273, 0.1251, 0.1241, 0.1826, 0.1579, 0.1270, 0.1300])
tensor([0.1215, 0.1228, 0.1228, 0.1448, 0.2363, 0.1291, 0.1228])
tensor([0.1438])
tensor(-1.)
65/500


100%|██████████| 10/10 [06:33<00:00, 39.33s/it]


Winners:  {1: 5, 0: 5}

Policy Loss 0.014870877377688885
Value Loss 0.8739875555038452
Examples:
tensor([0.1716, 0.1364, 0.1692, 0.1948, 0.1713, 0.1599, 0.1762])
tensor([0.1284, 0.1290, 0.1624, 0.1477, 0.1529, 0.1499, 0.1297])
tensor([0.4219])
tensor(1.)

Policy Loss 0.01514998497441411
Value Loss 0.8529837876558304
Examples:
tensor([0.0944, 0.1311, 0.1576, 0.1368, 0.1105, 0.1014, 0.0979])
tensor([0.1172, 0.1172, 0.1172, 0.2970, 0.1172, 0.1172, 0.1172])
tensor([0.0302])
tensor(1.)
66/500


100%|██████████| 10/10 [06:24<00:00, 38.50s/it]


Winners:  {1: 3, 0: 7}

Policy Loss 0.0184473330155015
Value Loss 1.2967923283576965
Examples:
tensor([0.1191, 0.1322, 0.1596, 0.1936, 0.1208, 0.1469, 0.1079])
tensor([0.1191, 0.1191, 0.1191, 0.2731, 0.1316, 0.1191, 0.1191])
tensor([0.0952])
tensor(1.)

Policy Loss 0.01810077391564846
Value Loss 1.0989640355110168
Examples:
tensor([0.1131, 0.1308, 0.1358, 0.1874, 0.1245, 0.1322, 0.1373])
tensor([0.1317, 0.1337, 0.1337, 0.1391, 0.1925, 0.1343, 0.1350])
tensor([-0.3809])
tensor(-1.)
67/500


100%|██████████| 10/10 [06:48<00:00, 40.84s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.0173038262873888
Value Loss 1.2260322570800781
Examples:
tensor([0.1136, 0.1227, 0.1319, 0.1610, 0.1399, 0.1081, 0.1245])
tensor([0.1237, 0.1445, 0.2406, 0.1237, 0.1225, 0.1225, 0.1225])
tensor([-0.0941])
tensor(1.)

Policy Loss 0.015759337693452835
Value Loss 1.090788871049881
Examples:
tensor([0.1473, 0.1509, 0.1692, 0.1531, 0.1692, 0.1592, 0.1207])
tensor([0.1253, 0.1399, 0.2129, 0.1478, 0.1253, 0.1259, 0.1228])
tensor([0.0586])
tensor(1.)
68/500


100%|██████████| 10/10 [06:53<00:00, 41.32s/it]


Winners:  {0: 3, 1: 7}

Policy Loss 0.013500578235834837
Value Loss 0.8204526901245117
Examples:
tensor([0.1115, 0.1497, 0.1473, 0.1457, 0.1377, 0.1412, 0.1225])
tensor([0.1247, 0.2562, 0.1228, 0.1247, 0.1235, 0.1235, 0.1247])
tensor([0.0952])
tensor(-1.)

Policy Loss 0.011859595077112317
Value Loss 0.8180867284536362
Examples:
tensor([0.1371, 0.1392, 0.1347, 0.1758, 0.1585, 0.1158, 0.1505])
tensor([0.1262, 0.1327, 0.2232, 0.1354, 0.1314, 0.1250, 0.1262])
tensor([0.0722])
tensor(-1.)
69/500


100%|██████████| 10/10 [06:44<00:00, 40.48s/it]


Winners:  {0: 6, 1: 4}

Policy Loss 0.016396882943809032
Value Loss 0.971636176109314
Examples:
tensor([0.1364, 0.1868, 0.1222, 0.1166, 0.1532, 0.1320, 0.1512])
tensor([0.1382, 0.1431, 0.1438, 0.1482, 0.1389, 0.1453, 0.1424])
tensor([-0.3077])
tensor(-1.)

Policy Loss 0.015971575863659382
Value Loss 0.9543518573045731
Examples:
tensor([0.1329, 0.1814, 0.1175, 0.1359, 0.1582, 0.1398, 0.1754])
tensor([0.1184, 0.1196, 0.1196, 0.2826, 0.1220, 0.1196, 0.1184])
tensor([0.0349])
tensor(1.)
70/500


100%|██████████| 10/10 [07:49<00:00, 46.95s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.011787998179594675
Value Loss 1.1874061425526936
Examples:
tensor([0.1022, 0.1747, 0.1140, 0.1394, 0.1598, 0.1066, 0.1218])
tensor([0.0000, 0.3911, 0.0000, 0.1520, 0.1520, 0.1528, 0.1520])
tensor([0.3536])
tensor(1.)

Policy Loss 0.012515456105271975
Value Loss 1.1273796757062275
Examples:
tensor([0.1319, 0.1489, 0.1491, 0.1868, 0.1462, 0.1408, 0.1047])
tensor([0.1229, 0.1273, 0.1464, 0.2342, 0.1247, 0.1229, 0.1217])
tensor([0.0446])
tensor(-1.)
71/500


100%|██████████| 10/10 [08:20<00:00, 50.08s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.017346042829255264
Value Loss 0.7868728041648865
Examples:
tensor([0.1194, 0.1163, 0.1465, 0.1358, 0.1616, 0.1372, 0.1281])
tensor([0.1262, 0.1367, 0.1380, 0.1541, 0.1939, 0.1262, 0.1249])
tensor([-0.0157])
tensor(-1.)

Policy Loss 0.017589947984864313
Value Loss 0.7209843297799429
Examples:
tensor([0.1225, 0.1711, 0.1415, 0.1493, 0.1628, 0.1339, 0.1281])
tensor([0.1284, 0.1265, 0.1265, 0.1240, 0.1271, 0.2399, 0.1277])
tensor([0.3121])
tensor(1.)
72/500


100%|██████████| 10/10 [06:14<00:00, 37.42s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.02868799865245819
Value Loss 1.0218077600002289
Examples:
tensor([0.1277, 0.1038, 0.1546, 0.1668, 0.1650, 0.1318, 0.1181])
tensor([0.1225, 0.1225, 0.1237, 0.1452, 0.2177, 0.1459, 0.1225])
tensor([0.1213])
tensor(1.)

Policy Loss 0.028120342642068863
Value Loss 0.966952309012413
Examples:
tensor([0.1383, 0.1033, 0.1144, 0.1804, 0.1899, 0.1106, 0.1437])
tensor([0.1375, 0.1375, 0.1497, 0.1410, 0.1431, 0.1424, 0.1489])
tensor([0.2072])
tensor(1.)
73/500


100%|██████████| 10/10 [09:04<00:00, 54.46s/it]


Winners:  {0: 8, 1: 2}

Policy Loss 0.02446844552954038
Value Loss 0.9888910253842672
Examples:
tensor([0.1334, 0.1331, 0.1578, 0.1760, 0.1838, 0.1742, 0.1454])
tensor([0.1177, 0.1177, 0.1177, 0.1195, 0.2909, 0.1189, 0.1177])
tensor([-0.1724])
tensor(-1.)

Policy Loss 0.021730312146246433
Value Loss 0.9124145607153574
Examples:
tensor([0.1040, 0.1232, 0.1181, 0.1325, 0.1605, 0.1559, 0.1267])
tensor([0.1206, 0.1206, 0.1218, 0.1387, 0.2515, 0.1249, 0.1218])
tensor([0.1581])
tensor(1.)
74/500


100%|██████████| 10/10 [06:30<00:00, 39.09s/it]


Winners:  {1: 4, 0: 6}

Policy Loss 0.013344654347747564
Value Loss 1.1623379588127136
Examples:
tensor([0.1361, 0.1340, 0.1256, 0.1196, 0.1380, 0.1869, 0.1421])
tensor([0.1306, 0.1306, 0.1745, 0.1660, 0.1293, 0.1319, 0.1373])
tensor([-0.1820])
tensor(1.)

Policy Loss 0.013431342784315348
Value Loss 1.0237447917461395
Examples:
tensor([0.1326, 0.1449, 0.1044, 0.1544, 0.1444, 0.1225, 0.1421])
tensor([0.1231, 0.1219, 0.1219, 0.1294, 0.1219, 0.2517, 0.1301])
tensor([-0.2196])
tensor(1.)
75/500


100%|██████████| 10/10 [07:14<00:00, 43.46s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.015590333379805088
Value Loss 1.0189170837402344
Examples:
tensor([0.1464, 0.1478, 0.1458, 0.1650, 0.1705, 0.1312, 0.1261])
tensor([0.1268, 0.1333, 0.1416, 0.1402, 0.1818, 0.1416, 0.1347])
tensor([0.1628])
tensor(-1.)

Policy Loss 0.015113320046414932
Value Loss 1.0079563359419506
Examples:
tensor([0.1266, 0.1303, 0.1323, 0.1557, 0.1928, 0.1252, 0.1263])
tensor([0.1249, 0.1249, 0.1224, 0.2441, 0.1339, 0.1249, 0.1249])
tensor([0.2061])
tensor(1.)
76/500


100%|██████████| 10/10 [07:58<00:00, 47.89s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.025015483299891155
Value Loss 1.1071452697118123
Examples:
tensor([0.1154, 0.1793, 0.1720, 0.1643, 0.1577, 0.1754, 0.1129])
tensor([0.1172, 0.2970, 0.1172, 0.1172, 0.1172, 0.1172, 0.1172])
tensor([-0.1155])
tensor(1.)

Policy Loss 0.02195329125970602
Value Loss 1.0410907169183095
Examples:
tensor([0.1064, 0.1324, 0.1499, 0.2028, 0.1155, 0.1173, 0.1165])
tensor([0.1295, 0.1275, 0.1605, 0.1416, 0.1704, 0.1416, 0.1288])
tensor([0.0908])
tensor(1.)
77/500


100%|██████████| 10/10 [07:28<00:00, 44.83s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.011752285994589329
Value Loss 1.0127907395362854
Examples:
tensor([0.1436, 0.1311, 0.1433, 0.1549, 0.1663, 0.1514, 0.1299])
tensor([0.1377, 0.1364, 0.1433, 0.1733, 0.1337, 0.1419, 0.1337])
tensor([-0.0334])
tensor(-1.)

Policy Loss 0.010747251566499472
Value Loss 0.9876951426267624
Examples:
tensor([0.1232, 0.1103, 0.1406, 0.1649, 0.1567, 0.1446, 0.1299])
tensor([0.1244, 0.1270, 0.1282, 0.2420, 0.1270, 0.1257, 0.1257])
tensor([-0.2355])
tensor(-1.)
78/500


100%|██████████| 10/10 [05:59<00:00, 35.93s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.009754359722137451
Value Loss 1.0054804980754852
Examples:
tensor([0.1432, 0.1325, 0.1619, 0.1623, 0.1680, 0.1607, 0.1509])
tensor([0.1337, 0.1492, 0.1405, 0.1700, 0.1405, 0.1324, 0.1337])
tensor([-0.2169])
tensor(-1.)

Policy Loss 0.00903360836673528
Value Loss 1.003906473517418
Examples:
tensor([0.1113, 0.1509, 0.1379, 0.1100, 0.1260, 0.1384, 0.0962])
tensor([0.1292, 0.1292, 0.1305, 0.1324, 0.1311, 0.1305, 0.2172])
tensor([0.0106])
tensor(-1.)
79/500


100%|██████████| 10/10 [07:03<00:00, 42.31s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.010587915778160095
Value Loss 0.9945613443851471
Examples:
tensor([0.1152, 0.1257, 0.1899, 0.1441, 0.1292, 0.1546, 0.1551])
tensor([0.1256, 0.1244, 0.2518, 0.1244, 0.1250, 0.1250, 0.1238])
tensor([0.0238])
tensor(-1.)

Policy Loss 0.010977484751492739
Value Loss 0.9952634125947952
Examples:
tensor([0.0944, 0.1083, 0.1837, 0.1363, 0.1393, 0.1432, 0.1340])
tensor([0.0000, 0.1533, 0.1746, 0.2090, 0.1596, 0.1518, 0.1518])
tensor([-0.0514])
tensor(-1.)
80/500


100%|██████████| 10/10 [05:50<00:00, 35.07s/it]


Winners:  {0: 3, 1: 7}

Policy Loss 0.008417935110628605
Value Loss 0.96876260638237
Examples:
tensor([0.1414, 0.1506, 0.1592, 0.1581, 0.1518, 0.1557, 0.1270])
tensor([0.1311, 0.1324, 0.1554, 0.1585, 0.1508, 0.1406, 0.1311])
tensor([-0.0546])
tensor(-1.)

Policy Loss 0.009755254024639726
Value Loss 0.931070402264595
Examples:
tensor([0.1467, 0.1577, 0.1531, 0.1396, 0.1359, 0.1614, 0.1345])
tensor([0.1323, 0.1323, 0.1323, 0.1323, 0.3386, 0.1323, 0.0000])
tensor([0.2289])
tensor(1.)
81/500


100%|██████████| 10/10 [08:06<00:00, 48.62s/it]


Winners:  {0: 4, 1: 6}

Policy Loss 0.020565884187817574
Value Loss 0.8915510376294454
Examples:
tensor([0.1464, 0.1352, 0.1438, 0.1600, 0.1635, 0.1598, 0.1417])
tensor([0.1237, 0.1237, 0.1237, 0.2441, 0.1274, 0.1313, 0.1262])
tensor([-0.1131])
tensor(-1.)

Policy Loss 0.01931187075873216
Value Loss 0.8417190710703532
Examples:
tensor([0.1455, 0.1151, 0.1528, 0.1615, 0.1364, 0.1541, 0.1435])
tensor([0.1392, 0.1539, 0.1618, 0.1464, 0.1351, 0.1325, 0.1311])
tensor([0.0263])
tensor(-1.)
82/500


100%|██████████| 10/10 [07:10<00:00, 43.06s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.013281695544719696
Value Loss 1.1266220808029175
Examples:
tensor([0.1335, 0.1361, 0.1288, 0.1682, 0.1594, 0.1744, 0.1298])
tensor([0.1172, 0.1172, 0.1172, 0.1172, 0.1172, 0.2970, 0.1172])
tensor([-0.0500])
tensor(-1.)

Policy Loss 0.011649019783362746
Value Loss 1.073368787765503
Examples:
tensor([0.1027, 0.1352, 0.1321, 0.1724, 0.1807, 0.1124, 0.1213])
tensor([0.1236, 0.1236, 0.1236, 0.1685, 0.2121, 0.1236, 0.1249])
tensor([-0.0777])
tensor(-1.)
83/500


100%|██████████| 10/10 [06:33<00:00, 39.37s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.014661363791674376
Value Loss 0.874074786901474
Examples:
tensor([0.1059, 0.1393, 0.1375, 0.1367, 0.1500, 0.1153, 0.1137])
tensor([0.1299, 0.1525, 0.1571, 0.1451, 0.1394, 0.1394, 0.1366])
tensor([0.0623])
tensor(1.)

Policy Loss 0.011516198515892029
Value Loss 0.8453334122896194
Examples:
tensor([0.1170, 0.1280, 0.1306, 0.1683, 0.1402, 0.1316, 0.1203])
tensor([0.1281, 0.1281, 0.1518, 0.1580, 0.1712, 0.1333, 0.1294])
tensor([-0.0652])
tensor(-1.)
84/500


100%|██████████| 10/10 [06:26<00:00, 38.66s/it]


Winners:  {0: 4, 1: 6}

Policy Loss 0.011851986404508352
Value Loss 0.9393936693668365
Examples:
tensor([0.1229, 0.1427, 0.1359, 0.1700, 0.1660, 0.1293, 0.1218])
tensor([0.1217, 0.1229, 0.1229, 0.2331, 0.1486, 0.1254, 0.1254])
tensor([0.2281])
tensor(1.)

Policy Loss 0.01525333826430142
Value Loss 0.9343327879905701
Examples:
tensor([0.1355, 0.1364, 0.1083, 0.1835, 0.1676, 0.1311, 0.1219])
tensor([0.1524, 0.1619, 0.0000, 0.1928, 0.1651, 0.1651, 0.1627])
tensor([-0.2124])
tensor(-1.)
85/500


100%|██████████| 10/10 [07:32<00:00, 45.22s/it]


Winners:  {1: 5, 0: 5}

Policy Loss 0.023880136509736378
Value Loss 1.0719606479008992
Examples:
tensor([0.1073, 0.1048, 0.0865, 0.1395, 0.1468, 0.1473, 0.1416])
tensor([0.1275, 0.1307, 0.1496, 0.1244, 0.1941, 0.1409, 0.1327])
tensor([-0.0522])
tensor(-1.)

Policy Loss 0.02044542816778024
Value Loss 1.0106167495250702
Examples:
tensor([0.1350, 0.1449, 0.1588, 0.1556, 0.1612, 0.1447, 0.1349])
tensor([0.1348, 0.1375, 0.1445, 0.1783, 0.1445, 0.1321, 0.1282])
tensor([-0.1605])
tensor(-1.)
86/500


100%|██████████| 10/10 [07:47<00:00, 46.76s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.013270710594952106
Value Loss 0.9993669390678406
Examples:
tensor([0.1511, 0.1545, 0.1631, 0.1574, 0.1320, 0.1204, 0.1328])
tensor([0.1287, 0.1313, 0.2008, 0.1366, 0.1380, 0.1339, 0.1306])
tensor([-0.0430])
tensor(-1.)

Policy Loss 0.012714625025788942
Value Loss 0.9591624637444814
Examples:
tensor([0.1551, 0.1561, 0.1598, 0.1802, 0.1425, 0.1283, 0.1125])
tensor([0.1368, 0.1922, 0.1410, 0.1497, 0.1263, 0.1263, 0.1276])
tensor([0.0812])
tensor(1.)
87/500


100%|██████████| 10/10 [06:39<00:00, 39.96s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.010714628733694553
Value Loss 1.0556448698043823
Examples:
tensor([0.1227, 0.1421, 0.1614, 0.1629, 0.1362, 0.1093, 0.1071])
tensor([0.1734, 0.1350, 0.1405, 0.1405, 0.1378, 0.1364, 0.1364])
tensor([0.0346])
tensor(1.)

Policy Loss 0.010511054657399654
Value Loss 1.0324025452136993
Examples:
tensor([0.1574, 0.1390, 0.1565, 0.1508, 0.1416, 0.1570, 0.1187])
tensor([0.1296, 0.1335, 0.2094, 0.1376, 0.1309, 0.1296, 0.1296])
tensor([-0.1285])
tensor(-1.)
88/500


100%|██████████| 10/10 [06:40<00:00, 40.01s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.01124241016805172
Value Loss 1.073466420173645
Examples:
tensor([0.1253, 0.1188, 0.1395, 0.1411, 0.1419, 0.1144, 0.1249])
tensor([0.1464, 0.1338, 0.1684, 0.1365, 0.1365, 0.1406, 0.1379])
tensor([-0.0052])
tensor(-1.)

Policy Loss 0.011410662438720465
Value Loss 1.016252726316452
Examples:
tensor([0.1741, 0.1401, 0.1810, 0.1283, 0.1693, 0.1388, 0.1525])
tensor([0.1351, 0.1365, 0.1701, 0.1392, 0.1406, 0.1406, 0.1378])
tensor([-0.1136])
tensor(-1.)
89/500


100%|██████████| 10/10 [08:03<00:00, 48.38s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.022722655907273293
Value Loss 1.025177260239919
Examples:
tensor([0.1439, 0.1224, 0.1228, 0.1344, 0.1374, 0.1180, 0.1220])
tensor([0.1801, 0.1375, 0.1431, 0.1362, 0.1348, 0.1348, 0.1335])
tensor([0.1870])
tensor(-1.)

Policy Loss 0.02033580094575882
Value Loss 1.0010579824447632
Examples:
tensor([0.1452, 0.1418, 0.1150, 0.1434, 0.1315, 0.1789, 0.1325])
tensor([0.1172, 0.1172, 0.1172, 0.1172, 0.1172, 0.1172, 0.2970])
tensor([0.0888])
tensor(1.)
90/500


100%|██████████| 10/10 [09:18<00:00, 55.84s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.01555636121580998
Value Loss 1.0071463386217754
Examples:
tensor([0.1100, 0.1388, 0.1303, 0.1290, 0.1149, 0.0927, 0.1460])
tensor([0.1339, 0.1352, 0.1352, 0.1421, 0.1635, 0.1479, 0.1421])
tensor([-0.0368])
tensor(-1.)

Policy Loss 0.014527585202207169
Value Loss 0.9810773233572642
Examples:
tensor([0.1433, 0.1480, 0.1551, 0.1465, 0.1679, 0.1354, 0.1593])
tensor([0.1172, 0.2970, 0.1172, 0.1172, 0.1172, 0.1172, 0.1172])
tensor([-0.1026])
tensor(-1.)
91/500


100%|██████████| 10/10 [06:16<00:00, 37.61s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.01043470436707139
Value Loss 0.9624151587486267
Examples:
tensor([0.1458, 0.1469, 0.1421, 0.1694, 0.1441, 0.1344, 0.1299])
tensor([0.1496, 0.1437, 0.1423, 0.1466, 0.1451, 0.1262, 0.1466])
tensor([0.0910])
tensor(1.)

Policy Loss 0.009580003563314676
Value Loss 0.9488999992609024
Examples:
tensor([0.1275, 0.1530, 0.1249, 0.1471, 0.1195, 0.1317, 0.1201])
tensor([0.1354, 0.1367, 0.1354, 0.1452, 0.1526, 0.1481, 0.1466])
tensor([-0.0882])
tensor(1.)
92/500


100%|██████████| 10/10 [07:34<00:00, 45.47s/it]


Winners:  {0: 6, 1: 4}

Policy Loss 0.011541500221937895
Value Loss 0.9454663991928101
Examples:
tensor([0.1332, 0.1458, 0.1165, 0.1742, 0.1439, 0.1161, 0.1533])
tensor([0.1557, 0.1353, 0.1367, 0.1437, 0.1496, 0.1409, 0.1381])
tensor([-0.0426])
tensor(1.)

Policy Loss 0.010375458048656583
Value Loss 0.9253612905740738
Examples:
tensor([0.1361, 0.1129, 0.1453, 0.1593, 0.1279, 0.1258, 0.1428])
tensor([0.1255, 0.2539, 0.1248, 0.1218, 0.1218, 0.1242, 0.1280])
tensor([0.2054])
tensor(-1.)
93/500


100%|██████████| 10/10 [06:59<00:00, 41.92s/it]


Winners:  {0: 6, 1: 4}

Policy Loss 0.01175479730591178
Value Loss 0.9304514229297638
Examples:
tensor([0.1441, 0.1284, 0.1193, 0.1340, 0.1145, 0.1211, 0.1547])
tensor([0.1387, 0.1280, 0.1332, 0.1401, 0.1359, 0.1853, 0.1387])
tensor([0.2933])
tensor(1.)

Policy Loss 0.010577630833722651
Value Loss 0.8835992217063904
Examples:
tensor([0.1323, 0.1354, 0.1403, 0.1343, 0.1274, 0.1343, 0.1540])
tensor([0.1415, 0.1293, 0.1332, 0.1346, 0.1359, 0.1853, 0.1401])
tensor([0.3316])
tensor(1.)
94/500


100%|██████████| 10/10 [05:56<00:00, 35.67s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.014078093692660332
Value Loss 1.0617714524269104
Examples:
tensor([0.1247, 0.1471, 0.1440, 0.1478, 0.1311, 0.1246, 0.1466])
tensor([0.1351, 0.1351, 0.1393, 0.1684, 0.1379, 0.1393, 0.1449])
tensor([0.1179])
tensor(-1.)

Policy Loss 0.013376362156122923
Value Loss 1.0075580775737762
Examples:
tensor([0.1535, 0.1430, 0.1427, 0.1382, 0.1804, 0.1637, 0.0860])
tensor([0.1172, 0.1172, 0.1172, 0.1172, 0.2970, 0.1172, 0.1172])
tensor([0.2166])
tensor(1.)
95/500


100%|██████████| 10/10 [07:48<00:00, 46.85s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.01625022618100047
Value Loss 1.0825051665306091
Examples:
tensor([0.1169, 0.1235, 0.1362, 0.1637, 0.1426, 0.1437, 0.1300])
tensor([0.1243, 0.1231, 0.1243, 0.2529, 0.1243, 0.1256, 0.1256])
tensor([0.1484])
tensor(1.)

Policy Loss 0.014346257783472538
Value Loss 1.036197006702423
Examples:
tensor([0.1403, 0.1319, 0.1618, 0.1767, 0.1661, 0.1647, 0.1270])
tensor([0.1303, 0.1316, 0.1370, 0.1944, 0.1342, 0.1383, 0.1342])
tensor([-0.0329])
tensor(1.)
96/500


100%|██████████| 10/10 [08:19<00:00, 49.97s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.017950695008039474
Value Loss 0.9588328798611959
Examples:
tensor([0.1239, 0.1183, 0.1311, 0.1280, 0.1290, 0.1535, 0.1226])
tensor([0.1478, 0.1285, 0.1650, 0.1351, 0.1463, 0.1449, 0.1324])
tensor([-0.0251])
tensor(1.)

Policy Loss 0.017511021345853806
Value Loss 0.9203742444515228
Examples:
tensor([0.1302, 0.1647, 0.1636, 0.0999, 0.1569, 0.1622, 0.1306])
tensor([0.0000, 0.2031, 0.1688, 0.1913, 0.2244, 0.2124, 0.0000])
tensor([-0.1870])
tensor(-1.)
97/500


100%|██████████| 10/10 [08:03<00:00, 48.35s/it]


Winners:  {1: 4, 0: 6}

Policy Loss 0.010737723981340727
Value Loss 0.8766302466392517
Examples:
tensor([0.1359, 0.1304, 0.1546, 0.1632, 0.1599, 0.1386, 0.1188])
tensor([0.1172, 0.1172, 0.2970, 0.1172, 0.1172, 0.1172, 0.1172])
tensor([-0.1986])
tensor(1.)

Policy Loss 0.010774616928150257
Value Loss 0.8289059400558472
Examples:
tensor([0.1381, 0.1298, 0.1518, 0.1535, 0.1596, 0.1357, 0.1310])
tensor([0.1267, 0.1229, 0.2551, 0.1242, 0.1242, 0.1229, 0.1242])
tensor([-0.0432])
tensor(-1.)
98/500


100%|██████████| 10/10 [08:25<00:00, 50.59s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.015590615260104338
Value Loss 1.0418640573819478
Examples:
tensor([0.1429, 0.1484, 0.1415, 0.1723, 0.1615, 0.1565, 0.1386])
tensor([0.1217, 0.1229, 0.1241, 0.2319, 0.1524, 0.1241, 0.1229])
tensor([0.0320])
tensor(-1.)

Policy Loss 0.015162253907571236
Value Loss 0.9422021210193634
Examples:
tensor([0.1439, 0.1243, 0.1304, 0.1562, 0.1956, 0.1624, 0.1577])
tensor([0.1172, 0.1172, 0.1172, 0.1172, 0.1172, 0.1172, 0.2970])
tensor([0.3830])
tensor(1.)
99/500


100%|██████████| 10/10 [06:38<00:00, 39.89s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.011833928525447845
Value Loss 1.110541820526123
Examples:
tensor([0.1401, 0.1237, 0.1296, 0.1670, 0.1691, 0.1573, 0.1266])
tensor([0.1204, 0.1204, 0.1222, 0.2549, 0.1260, 0.1344, 0.1216])
tensor([0.0448])
tensor(1.)

Policy Loss 0.01178516517393291
Value Loss 1.0213168561458588
Examples:
tensor([0.1157, 0.1162, 0.1370, 0.1657, 0.1509, 0.1701, 0.1281])
tensor([0.1247, 0.1272, 0.1378, 0.1975, 0.1570, 0.1298, 0.1260])
tensor([0.0153])
tensor(-1.)
100/500


100%|██████████| 10/10 [07:41<00:00, 46.15s/it]


Winners:  {0: 8, 1: 2}

Policy Loss 0.0198527742177248
Value Loss 0.9452177882194519
Examples:
tensor([0.1288, 0.1177, 0.1331, 0.1751, 0.1746, 0.1759, 0.1411])
tensor([0.1161, 0.1161, 0.1161, 0.3031, 0.1161, 0.1161, 0.1166])
tensor([0.0229])
tensor(1.)

Policy Loss 0.01751521392725408
Value Loss 0.9030216485261917
Examples:
tensor([0.1397, 0.1375, 0.1291, 0.1806, 0.1667, 0.1251, 0.1463])
tensor([0.1203, 0.1197, 0.1215, 0.2732, 0.1234, 0.1209, 0.1209])
tensor([-0.0706])
tensor(1.)
101/500


100%|██████████| 10/10 [06:23<00:00, 38.38s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.01320051634684205
Value Loss 0.9469841718673706
Examples:
tensor([0.1525, 0.1247, 0.1274, 0.1476, 0.1829, 0.1319, 0.1273])
tensor([0.1299, 0.2017, 0.1436, 0.1312, 0.1312, 0.1325, 0.1299])
tensor([-0.4649])
tensor(-1.)

Policy Loss 0.013771130703389645
Value Loss 0.9270882457494736
Examples:
tensor([0.1126, 0.1512, 0.1314, 0.1454, 0.1551, 0.1127, 0.1164])
tensor([0.1545, 0.1317, 0.1545, 0.1310, 0.1434, 0.1272, 0.1577])
tensor([-0.1180])
tensor(1.)
102/500


100%|██████████| 10/10 [05:51<00:00, 35.16s/it]


Winners:  {0: 4, 1: 6}

Policy Loss 0.012192445807158947
Value Loss 0.9926900863647461
Examples:
tensor([0.1283, 0.1339, 0.1397, 0.1487, 0.1924, 0.1445, 0.1451])
tensor([0.1231, 0.1268, 0.2040, 0.1256, 0.1596, 0.1354, 0.1256])
tensor([0.0022])
tensor(-1.)

Policy Loss 0.011953314067795873
Value Loss 0.952821671962738
Examples:
tensor([0.1176, 0.1234, 0.1182, 0.1682, 0.1957, 0.1479, 0.1093])
tensor([0.1215, 0.1228, 0.1259, 0.1246, 0.2573, 0.1234, 0.1246])
tensor([0.1986])
tensor(1.)
103/500


100%|██████████| 10/10 [09:00<00:00, 54.03s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.021948102861642838
Value Loss 0.8405085603396097
Examples:
tensor([0.1348, 0.1352, 0.1472, 0.1456, 0.1813, 0.1625, 0.1337])
tensor([0.1252, 0.1265, 0.1265, 0.1412, 0.1384, 0.2170, 0.1252])
tensor([0.0327])
tensor(1.)

Policy Loss 0.02239578279356162
Value Loss 0.8031212588151296
Examples:
tensor([0.1355, 0.1567, 0.1549, 0.1510, 0.1624, 0.1243, 0.1265])
tensor([0.1257, 0.1270, 0.1264, 0.1559, 0.2147, 0.1257, 0.1245])
tensor([0.1828])
tensor(-1.)
104/500


100%|██████████| 10/10 [06:38<00:00, 39.90s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.016046888194978237
Value Loss 1.1526987552642822
Examples:
tensor([0.1153, 0.1335, 0.1247, 0.1637, 0.1180, 0.1107, 0.1126])
tensor([0.1379, 0.1365, 0.1338, 0.1618, 0.1570, 0.1406, 0.1325])
tensor([0.0185])
tensor(-1.)

Policy Loss 0.01427097199484706
Value Loss 1.071760669350624
Examples:
tensor([0.1514, 0.1497, 0.1700, 0.1658, 0.1669, 0.1575, 0.1453])
tensor([0.1282, 0.1282, 0.1256, 0.1696, 0.1445, 0.1512, 0.1527])
tensor([-0.0210])
tensor(-1.)
105/500


100%|██████████| 10/10 [07:24<00:00, 44.40s/it]


Winners:  {1: 3, 0: 7}

Policy Loss 0.018288442865014076
Value Loss 1.038377583026886
Examples:
tensor([0.1413, 0.1497, 0.1524, 0.1889, 0.1998, 0.1698, 0.1312])
tensor([0.1361, 0.1361, 0.1374, 0.1388, 0.3136, 0.1381, 0.0000])
tensor([-0.0192])
tensor(-1.)

Policy Loss 0.01745265582576394
Value Loss 1.014406144618988
Examples:
tensor([0.1070, 0.1127, 0.1127, 0.1613, 0.1438, 0.1119, 0.1088])
tensor([0.1361, 0.1348, 0.1361, 0.1810, 0.1445, 0.1348, 0.1327])
tensor([-0.0210])
tensor(1.)
106/500


100%|██████████| 10/10 [07:47<00:00, 46.76s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.016003160116573174
Value Loss 0.796514610449473
Examples:
tensor([0.1520, 0.1194, 0.1907, 0.1689, 0.1670, 0.1464, 0.1450])
tensor([0.1179, 0.1185, 0.1185, 0.1203, 0.2885, 0.1185, 0.1179])
tensor([0.4995])
tensor(1.)

Policy Loss 0.015648283064365387
Value Loss 0.7485316495100657
Examples:
tensor([0.1445, 0.1277, 0.1624, 0.1611, 0.1475, 0.1293, 0.1457])
tensor([0.1320, 0.1738, 0.1809, 0.1288, 0.1281, 0.1281, 0.1281])
tensor([-0.0583])
tensor(1.)
107/500


100%|██████████| 10/10 [06:04<00:00, 36.45s/it]


Winners:  {0: 2, 1: 8}

Policy Loss 0.010743561200797558
Value Loss 0.755840539932251
Examples:
tensor([0.1364, 0.1380, 0.1545, 0.1538, 0.1640, 0.1209, 0.1574])
tensor([0.1200, 0.1200, 0.1200, 0.1200, 0.2767, 0.1231, 0.1200])
tensor([0.4583])
tensor(1.)

Policy Loss 0.01057579810731113
Value Loss 0.7068596333265305
Examples:
tensor([0.1226, 0.1508, 0.1647, 0.1663, 0.1482, 0.1447, 0.1417])
tensor([0.1416, 0.1549, 0.1466, 0.1327, 0.1381, 0.1430, 0.1430])
tensor([-0.2759])
tensor(-1.)
108/500


100%|██████████| 10/10 [06:51<00:00, 41.18s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.011987303073207537
Value Loss 0.8066879113515218
Examples:
tensor([0.1530, 0.1426, 0.1381, 0.1578, 0.1867, 0.1324, 0.1325])
tensor([0.1217, 0.1235, 0.2551, 0.1235, 0.1260, 0.1254, 0.1248])
tensor([-0.6339])
tensor(-1.)

Policy Loss 0.012629504160334667
Value Loss 0.7855929533640543
Examples:
tensor([0.1184, 0.1305, 0.1580, 0.1797, 0.1302, 0.1085, 0.1299])
tensor([0.1174, 0.1174, 0.1180, 0.2945, 0.1180, 0.1174, 0.1174])
tensor([-0.2456])
tensor(-1.)
109/500


100%|██████████| 10/10 [05:31<00:00, 33.11s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.015585366636514664
Value Loss 1.074819803237915
Examples:
tensor([0.1346, 0.1193, 0.1623, 0.2059, 0.1540, 0.1341, 0.1511])
tensor([0.1193, 0.1223, 0.1229, 0.2709, 0.1223, 0.1211, 0.1211])
tensor([-0.2679])
tensor(-1.)

Policy Loss 0.015145343728363514
Value Loss 1.0717833042144775
Examples:
tensor([0.1409, 0.1145, 0.1823, 0.1738, 0.1586, 0.1518, 0.1586])
tensor([0.1251, 0.1257, 0.1446, 0.1257, 0.1257, 0.1239, 0.2291])
tensor([0.6161])
tensor(-1.)
110/500


100%|██████████| 10/10 [07:17<00:00, 43.78s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.012825879734009504
Value Loss 0.9965140223503113
Examples:
tensor([0.1083, 0.1224, 0.1676, 0.1627, 0.1278, 0.1199, 0.1320])
tensor([0.1436, 0.2121, 0.0000, 0.1443, 0.1443, 0.2121, 0.1436])
tensor([0.6450])
tensor(-1.)

Policy Loss 0.01196778123266995
Value Loss 0.9326413571834564
Examples:
tensor([0.1532, 0.1353, 0.1581, 0.1925, 0.1367, 0.1408, 0.1249])
tensor([0.1294, 0.1294, 0.2243, 0.1294, 0.1294, 0.1294, 0.1287])
tensor([-0.1813])
tensor(-1.)
111/500


100%|██████████| 10/10 [06:45<00:00, 40.56s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.01673711184412241
Value Loss 1.0968032479286194
Examples:
tensor([0.1267, 0.1211, 0.1446, 0.1690, 0.1307, 0.1228, 0.1283])
tensor([0.1263, 0.1348, 0.1638, 0.1582, 0.1551, 0.1335, 0.1282])
tensor([-0.0461])
tensor(1.)

Policy Loss 0.015460651367902756
Value Loss 1.0121125876903534
Examples:
tensor([0.1196, 0.1017, 0.1419, 0.1485, 0.1532, 0.1275, 0.1295])
tensor([0.1194, 0.1213, 0.1200, 0.1200, 0.2767, 0.1206, 0.1219])
tensor([0.3170])
tensor(-1.)
112/500


100%|██████████| 10/10 [07:50<00:00, 47.03s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.051993937542041145
Value Loss 0.7325464685757955
Examples:
tensor([0.1390, 0.1253, 0.1855, 0.1658, 0.1480, 0.1260, 0.1251])
tensor([0.1264, 0.1342, 0.1329, 0.1369, 0.1924, 0.1483, 0.1289])
tensor([-0.2074])
tensor(0.)

Policy Loss 0.039816698990762234
Value Loss 0.757037361462911
Examples:
tensor([0.1877, 0.1398, 0.1586, 0.1829, 0.1541, 0.1437, 0.1208])
tensor([0.1197, 0.1197, 0.1197, 0.1203, 0.2814, 0.1197, 0.1197])
tensor([0.3970])
tensor(1.)
113/500


100%|██████████| 10/10 [07:02<00:00, 42.23s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.012037361040711403
Value Loss 0.9115126132965088
Examples:
tensor([0.1350, 0.1361, 0.1689, 0.1631, 0.1567, 0.1222, 0.1264])
tensor([0.1351, 0.1351, 0.1406, 0.1683, 0.1508, 0.1351, 0.1351])
tensor([-0.0341])
tensor(1.)

Policy Loss 0.014469967689365149
Value Loss 0.7883807718753815
Examples:
tensor([0.1394, 0.1393, 0.1551, 0.1436, 0.1621, 0.1273, 0.1363])
tensor([0.1514, 0.1529, 0.1915, 0.1514, 0.1804, 0.0000, 0.1724])
tensor([-0.6360])
tensor(-1.)
114/500


100%|██████████| 10/10 [07:06<00:00, 42.61s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.009712349157780409
Value Loss 1.0123094320297241
Examples:
tensor([0.1163, 0.1218, 0.1398, 0.1567, 0.1350, 0.1276, 0.1224])
tensor([0.1336, 0.1336, 0.1391, 0.1699, 0.1537, 0.1336, 0.1363])
tensor([0.0098])
tensor(1.)

Policy Loss 0.009505008114501834
Value Loss 0.9592903107404709
Examples:
tensor([0.1305, 0.1332, 0.1159, 0.1505, 0.1236, 0.1273, 0.1105])
tensor([0.1364, 0.1364, 0.1392, 0.1717, 0.1463, 0.1350, 0.1350])
tensor([0.0400])
tensor(1.)
115/500


100%|██████████| 10/10 [07:30<00:00, 45.01s/it]


Winners:  {1: 3, 0: 7}

Policy Loss 0.01189294271171093
Value Loss 1.0987828373908997
Examples:
tensor([0.1377, 0.1389, 0.1391, 0.1734, 0.1437, 0.1176, 0.1439])
tensor([0.1331, 0.1331, 0.1331, 0.1337, 0.1617, 0.1538, 0.1515])
tensor([-0.4240])
tensor(-1.)

Policy Loss 0.012256674002856016
Value Loss 1.0674520283937454
Examples:
tensor([0.1384, 0.1514, 0.0727, 0.1133, 0.1418, 0.0597, 0.1382])
tensor([0.1487, 0.1443, 0.1644, 0.0000, 0.1652, 0.1694, 0.2079])
tensor([0.3772])
tensor(1.)
116/500


100%|██████████| 10/10 [06:01<00:00, 36.19s/it]


Winners:  {0: 8, 1: 2}

Policy Loss 0.010779505595564842
Value Loss 0.9611433446407318
Examples:
tensor([0.1422, 0.1424, 0.1387, 0.1497, 0.1944, 0.1623, 0.1412])
tensor([0.1290, 0.1290, 0.1303, 0.1608, 0.1849, 0.1356, 0.1303])
tensor([0.0325])
tensor(-1.)

Policy Loss 0.010265333810821176
Value Loss 0.9617729187011719
Examples:
tensor([0.1346, 0.1422, 0.1347, 0.1266, 0.1590, 0.1488, 0.1044])
tensor([0.1212, 0.1212, 0.1212, 0.2617, 0.1313, 0.1224, 0.1212])
tensor([0.3275])
tensor(1.)
117/500


100%|██████████| 10/10 [06:59<00:00, 41.90s/it]


Winners:  {1: 5, 0: 5}

Policy Loss 0.015908327884972095
Value Loss 1.003216286500295
Examples:
tensor([0.1205, 0.1421, 0.1371, 0.1677, 0.1462, 0.1101, 0.1530])
tensor([0.0000, 0.1722, 0.1605, 0.1679, 0.1783, 0.1605, 0.1605])
tensor([0.1173])
tensor(-1.)

Policy Loss 0.014139429355661074
Value Loss 0.9595960279305776
Examples:
tensor([0.1280, 0.1415, 0.1490, 0.1644, 0.1923, 0.1319, 0.1409])
tensor([0.1231, 0.1238, 0.1424, 0.2407, 0.1238, 0.1225, 0.1238])
tensor([-0.1727])
tensor(-1.)
118/500


100%|██████████| 10/10 [07:45<00:00, 46.59s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.016442032530903816
Value Loss 0.9683370391527811
Examples:
tensor([0.1321, 0.1485, 0.1766, 0.1344, 0.1894, 0.1028, 0.1322])
tensor([0.1172, 0.2970, 0.1172, 0.1172, 0.1172, 0.1172, 0.1172])
tensor([0.1288])
tensor(-1.)

Policy Loss 0.014453051456560692
Value Loss 0.9137400190035502
Examples:
tensor([0.1244, 0.1592, 0.1654, 0.1518, 0.1355, 0.1308, 0.1331])
tensor([0.1246, 0.1284, 0.2485, 0.1246, 0.1234, 0.1259, 0.1246])
tensor([-0.0318])
tensor(1.)
119/500


100%|██████████| 10/10 [06:49<00:00, 40.96s/it]


Winners:  {1: 5, 0: 5}

Policy Loss 0.014385045506060123
Value Loss 1.0376977622509003
Examples:
tensor([0.1256, 0.1159, 0.1424, 0.1576, 0.1348, 0.1449, 0.1284])
tensor([0.0000, 0.3253, 0.1349, 0.1349, 0.1349, 0.1349, 0.1349])
tensor([-0.3967])
tensor(1.)

Policy Loss 0.015220063272863626
Value Loss 0.9963053166866302
Examples:
tensor([0.1654, 0.1468, 0.1698, 0.1606, 0.1600, 0.1739, 0.1589])
tensor([0.1409, 0.1466, 0.1473, 0.1268, 0.1437, 0.1481, 0.1466])
tensor([0.2346])
tensor(1.)
120/500


100%|██████████| 10/10 [08:35<00:00, 51.60s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.016231452425320942
Value Loss 0.8918109138806661
Examples:
tensor([0.1340, 0.1524, 0.1488, 0.1618, 0.1546, 0.1489, 0.1357])
tensor([0.1310, 0.1252, 0.1297, 0.2192, 0.1277, 0.1363, 0.1310])
tensor([-0.0689])
tensor(-1.)

Policy Loss 0.014341103533903757
Value Loss 0.8171018560727438
Examples:
tensor([0.1414, 0.1202, 0.1392, 0.1090, 0.1309, 0.1049, 0.1096])
tensor([0.1662, 0.1511, 0.2243, 0.0000, 0.1496, 0.1474, 0.1613])
tensor([0.5049])
tensor(1.)
121/500


100%|██████████| 10/10 [06:41<00:00, 40.17s/it]


Winners:  {0: 6, 1: 4}

Policy Loss 0.009480066131800413
Value Loss 1.0193182229995728
Examples:
tensor([0.1367, 0.1609, 0.1592, 0.1287, 0.1487, 0.1389, 0.1369])
tensor([0.1172, 0.1172, 0.1172, 0.1172, 0.1172, 0.2970, 0.1172])
tensor([0.1640])
tensor(1.)

Policy Loss 0.009905049577355385
Value Loss 0.9484103620052338
Examples:
tensor([0.1344, 0.1598, 0.1642, 0.1728, 0.1763, 0.1440, 0.1281])
tensor([0.1178, 0.1190, 0.1190, 0.2897, 0.1190, 0.1178, 0.1178])
tensor([0.1165])
tensor(1.)
122/500


100%|██████████| 10/10 [06:59<00:00, 41.99s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.014624750707298517
Value Loss 0.9023432433605194
Examples:
tensor([0.1223, 0.1486, 0.1581, 0.1811, 0.1517, 0.1454, 0.1323])
tensor([0.1261, 0.1261, 0.1919, 0.1807, 0.1267, 0.1242, 0.1242])
tensor([0.2906])
tensor(-1.)

Policy Loss 0.014938096050173044
Value Loss 0.8498087972402573
Examples:
tensor([0.0992, 0.1285, 0.1570, 0.1690, 0.1321, 0.1044, 0.1141])
tensor([0.1198, 0.1204, 0.1204, 0.2802, 0.1198, 0.1198, 0.1198])
tensor([0.1343])
tensor(1.)
123/500


100%|██████████| 10/10 [04:55<00:00, 29.56s/it]


Winners:  {1: 5, 0: 5}

Policy Loss 0.010881875175982714
Value Loss 0.9161697626113892
Examples:
tensor([0.1302, 0.1262, 0.1648, 0.1874, 0.1475, 0.1224, 0.1271])
tensor([0.1227, 0.1245, 0.1239, 0.1425, 0.1252, 0.2385, 0.1227])
tensor([0.3392])
tensor(-1.)

Policy Loss 0.010374415200203657
Value Loss 0.8869367688894272
Examples:
tensor([0.1361, 0.1236, 0.1785, 0.1565, 0.1621, 0.1620, 0.1187])
tensor([0.1249, 0.1340, 0.1268, 0.2220, 0.1423, 0.1249, 0.1249])
tensor([0.4137])
tensor(1.)
124/500


100%|██████████| 10/10 [07:09<00:00, 42.91s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.014798260293900967
Value Loss 0.948885460694631
Examples:
tensor([0.1023, 0.1301, 0.1751, 0.1520, 0.1399, 0.1090, 0.1076])
tensor([0.1259, 0.1441, 0.1674, 0.1477, 0.1303, 0.1462, 0.1384])
tensor([0.3319])
tensor(-1.)

Policy Loss 0.014176807521531979
Value Loss 0.9308509429295858
Examples:
tensor([0.0820, 0.1252, 0.1293, 0.1890, 0.1218, 0.1059, 0.1099])
tensor([0.1303, 0.1707, 0.1296, 0.1785, 0.1283, 0.1336, 0.1290])
tensor([0.3604])
tensor(1.)
125/500


100%|██████████| 10/10 [07:35<00:00, 45.51s/it]


Winners:  {1: 5, 0: 5}

Policy Loss 0.012073644126454989
Value Loss 0.8697773019472758
Examples:
tensor([0.1225, 0.1151, 0.1766, 0.1749, 0.1162, 0.1113, 0.1120])
tensor([0.1219, 0.1219, 0.2686, 0.1231, 0.1231, 0.1207, 0.1207])
tensor([-0.1006])
tensor(1.)

Policy Loss 0.011401775137831768
Value Loss 0.8263020217418671
Examples:
tensor([0.1417, 0.1258, 0.1904, 0.1486, 0.1255, 0.1126, 0.1358])
tensor([0.1176, 0.1188, 0.2921, 0.1188, 0.1176, 0.1176, 0.1176])
tensor([-0.0440])
tensor(1.)
126/500


100%|██████████| 10/10 [07:51<00:00, 47.12s/it]


Winners:  {0: 4, 1: 6}

Policy Loss 0.01634317512313525
Value Loss 0.9787175456682841
Examples:
tensor([0.1269, 0.1527, 0.1568, 0.1775, 0.1606, 0.1439, 0.1299])
tensor([0.1260, 0.1235, 0.1235, 0.2463, 0.1229, 0.1286, 0.1292])
tensor([-0.2001])
tensor(1.)

Policy Loss 0.016611445074280102
Value Loss 0.9835521479447683
Examples:
tensor([0.1285, 0.1312, 0.1630, 0.1722, 0.1427, 0.1492, 0.1406])
tensor([0.1249, 0.1300, 0.2242, 0.1366, 0.1346, 0.1236, 0.1261])
tensor([0.3173])
tensor(1.)
127/500


100%|██████████| 10/10 [06:38<00:00, 39.89s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.008674926357343793
Value Loss 0.805269718170166
Examples:
tensor([0.1207, 0.1495, 0.1874, 0.1412, 0.1270, 0.1176, 0.1193])
tensor([0.1195, 0.1207, 0.2685, 0.1294, 0.1219, 0.1207, 0.1195])
tensor([0.2115])
tensor(1.)

Policy Loss 0.009506841073743999
Value Loss 0.7774561643600464
Examples:
tensor([0.1471, 0.1565, 0.1832, 0.1478, 0.1271, 0.1137, 0.1328])
tensor([0.1222, 0.2160, 0.1682, 0.1259, 0.1234, 0.1222, 0.1222])
tensor([-0.2330])
tensor(1.)
128/500


100%|██████████| 10/10 [05:37<00:00, 33.70s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.01384343160316348
Value Loss 1.0855333805084229
Examples:
tensor([0.1458, 0.1541, 0.1693, 0.1450, 0.1260, 0.1284, 0.1370])
tensor([0.2113, 0.1295, 0.1308, 0.1334, 0.1295, 0.1334, 0.1321])
tensor([0.0928])
tensor(-1.)

Policy Loss 0.01278933510184288
Value Loss 1.0396428108215332
Examples:
tensor([0.1266, 0.1341, 0.1774, 0.1880, 0.1392, 0.1458, 0.1288])
tensor([0.1230, 0.1242, 0.1359, 0.1685, 0.1998, 0.1242, 0.1242])
tensor([0.3111])
tensor(1.)
129/500


100%|██████████| 10/10 [05:08<00:00, 30.81s/it]


Winners:  {1: 5, 0: 5}

Policy Loss 0.012288306839764118
Value Loss 1.2140198945999146
Examples:
tensor([0.1462, 0.1439, 0.1369, 0.1768, 0.1338, 0.1235, 0.1407])
tensor([0.1180, 0.1192, 0.2873, 0.1204, 0.1192, 0.1180, 0.1180])
tensor([0.2070])
tensor(1.)

Policy Loss 0.012198015348985791
Value Loss 1.137293502688408
Examples:
tensor([0.1447, 0.1336, 0.1452, 0.1444, 0.1488, 0.1357, 0.1249])
tensor([0.1344, 0.1578, 0.1824, 0.1318, 0.1292, 0.1378, 0.1266])
tensor([-0.0982])
tensor(-1.)
130/500


100%|██████████| 10/10 [07:17<00:00, 43.73s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.012015437707304955
Value Loss 0.9115907847881317
Examples:
tensor([0.1329, 0.1416, 0.1470, 0.1580, 0.1448, 0.1153, 0.1210])
tensor([0.1235, 0.1223, 0.2640, 0.1223, 0.1235, 0.1223, 0.1223])
tensor([0.0381])
tensor(1.)

Policy Loss 0.011224357644096017
Value Loss 0.9168638736009598
Examples:
tensor([0.1113, 0.1170, 0.1400, 0.1840, 0.1407, 0.1095, 0.1179])
tensor([0.1245, 0.1258, 0.1664, 0.1953, 0.1363, 0.1258, 0.1258])
tensor([-0.0175])
tensor(-1.)
131/500


100%|██████████| 10/10 [07:22<00:00, 44.21s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.039047115171949066
Value Loss 0.7118698358535767
Examples:
tensor([0.1298, 0.1354, 0.1545, 0.1508, 0.1386, 0.1391, 0.1449])
tensor([0.1648, 0.1491, 0.1785, 0.0000, 0.1432, 0.1767, 0.1877])
tensor([0.2590])
tensor(0.)

Policy Loss 0.031145987411340077
Value Loss 0.7182516654332479
Examples:
tensor([0.1323, 0.1468, 0.1998, 0.1382, 0.1512, 0.1701, 0.1323])
tensor([0.1335, 0.1295, 0.2093, 0.1403, 0.1321, 0.1270, 0.1282])
tensor([-0.0657])
tensor(-1.)
132/500


100%|██████████| 10/10 [06:41<00:00, 40.18s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.01980738155543804
Value Loss 1.1450677514076233
Examples:
tensor([0.1287, 0.1332, 0.1752, 0.1497, 0.1423, 0.1622, 0.1214])
tensor([0.1250, 0.1381, 0.1354, 0.1637, 0.1865, 0.1263, 0.1250])
tensor([0.1413])
tensor(-1.)

Policy Loss 0.01653647399507463
Value Loss 1.095764398574829
Examples:
tensor([0.1425, 0.1520, 0.1430, 0.1406, 0.1716, 0.1679, 0.1335])
tensor([0.1232, 0.1295, 0.1245, 0.1232, 0.1257, 0.2506, 0.1232])
tensor([0.1984])
tensor(1.)
133/500


100%|██████████| 10/10 [07:27<00:00, 44.76s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.012746750687559446
Value Loss 0.9537710150082906
Examples:
tensor([0.1188, 0.1085, 0.1122, 0.1976, 0.1726, 0.1239, 0.1356])
tensor([0.1251, 0.1263, 0.2157, 0.1551, 0.1263, 0.1263, 0.1251])
tensor([-0.2200])
tensor(-1.)

Policy Loss 0.013131091681619486
Value Loss 0.9285431702931722
Examples:
tensor([0.1250, 0.1483, 0.1540, 0.1747, 0.1364, 0.0874, 0.1512])
tensor([0.1172, 0.2970, 0.1172, 0.1172, 0.1172, 0.1172, 0.1172])
tensor([-0.2077])
tensor(-1.)
134/500


100%|██████████| 10/10 [07:32<00:00, 45.27s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.01041396614164114
Value Loss 1.0134893655776978
Examples:
tensor([0.1324, 0.1453, 0.1364, 0.1890, 0.1846, 0.1351, 0.1458])
tensor([0.1197, 0.1197, 0.1377, 0.2638, 0.1197, 0.1197, 0.1197])
tensor([0.1169])
tensor(1.)

Policy Loss 0.01031673583202064
Value Loss 0.9979394823312759
Examples:
tensor([0.1212, 0.1269, 0.1391, 0.1721, 0.1764, 0.1460, 0.1228])
tensor([0.1234, 0.1234, 0.1351, 0.1463, 0.2249, 0.1234, 0.1234])
tensor([-0.0992])
tensor(1.)
135/500


100%|██████████| 10/10 [05:51<00:00, 35.12s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.010525245685130358
Value Loss 1.0018498301506042
Examples:
tensor([0.1325, 0.1394, 0.1332, 0.1699, 0.1648, 0.1194, 0.1453])
tensor([0.1265, 0.1343, 0.1278, 0.2171, 0.1412, 0.1265, 0.1265])
tensor([0.0373])
tensor(1.)

Policy Loss 0.010727530810981989
Value Loss 0.9453840851783752
Examples:
tensor([0.1312, 0.1383, 0.1603, 0.1719, 0.1886, 0.1290, 0.1412])
tensor([0.1222, 0.1272, 0.1222, 0.1378, 0.2461, 0.1222, 0.1222])
tensor([0.1334])
tensor(-1.)
136/500


100%|██████████| 10/10 [05:29<00:00, 32.96s/it]


Winners:  {0: 4, 1: 6}

Policy Loss 0.01158026559278369
Value Loss 1.0401002764701843
Examples:
tensor([0.1261, 0.1355, 0.1351, 0.1729, 0.1488, 0.1083, 0.1210])
tensor([0.1259, 0.1246, 0.1350, 0.1804, 0.1823, 0.1259, 0.1259])
tensor([0.1636])
tensor(1.)

Policy Loss 0.011479605222120881
Value Loss 0.9921269863843918
Examples:
tensor([0.1682, 0.1732, 0.1402, 0.1816, 0.1596, 0.1623, 0.1209])
tensor([0.1187, 0.1199, 0.1199, 0.1261, 0.1187, 0.1187, 0.2778])
tensor([0.2785])
tensor(1.)
137/500


100%|██████████| 10/10 [17:45<00:00, 106.55s/it]


Winners:  {1: 5, 0: 5}

Policy Loss 0.014997894875705242
Value Loss 0.9671769738197327
Examples:
tensor([0.1293, 0.1363, 0.1715, 0.1843, 0.1722, 0.1377, 0.1318])
tensor([0.1413, 0.1378, 0.1486, 0.1442, 0.1658, 0.1285, 0.1338])
tensor([0.2877])
tensor(-1.)

Policy Loss 0.013998495182022452
Value Loss 0.9504854530096054
Examples:
tensor([0.0971, 0.1157, 0.1476, 0.1612, 0.1269, 0.1090, 0.1189])
tensor([0.1291, 0.1317, 0.1725, 0.1385, 0.1725, 0.1278, 0.1278])
tensor([0.1777])
tensor(1.)
138/500


100%|██████████| 10/10 [05:39<00:00, 33.94s/it]


Winners:  {1: 2, 0: 8}

Policy Loss 0.010774509981274605
Value Loss 0.895454615354538
Examples:
tensor([0.1332, 0.1311, 0.1656, 0.1538, 0.1495, 0.1422, 0.1214])
tensor([0.1259, 0.1297, 0.1297, 0.2294, 0.1297, 0.1284, 0.1272])
tensor([-0.1482])
tensor(-1.)

Policy Loss 0.011278032325208187
Value Loss 0.8535423874855042
Examples:
tensor([0.1500, 0.1659, 0.1781, 0.1570, 0.1779, 0.1444, 0.1355])
tensor([0.1251, 0.1264, 0.2190, 0.1397, 0.1397, 0.1251, 0.1251])
tensor([0.3545])
tensor(-1.)
139/500


100%|██████████| 10/10 [07:15<00:00, 43.51s/it]


Winners:  {1: 3, 0: 7}

Policy Loss 0.009681702591478825
Value Loss 1.0475075244903564
Examples:
tensor([0.1090, 0.1271, 0.1430, 0.1409, 0.1446, 0.1187, 0.1314])
tensor([0.1937, 0.1223, 0.1235, 0.1223, 0.1937, 0.1223, 0.1223])
tensor([0.2146])
tensor(1.)

Policy Loss 0.00984961143694818
Value Loss 1.0149118304252625
Examples:
tensor([0.1197, 0.1187, 0.1236, 0.1696, 0.1690, 0.1171, 0.1243])
tensor([0.1224, 0.1236, 0.1236, 0.2440, 0.1380, 0.1248, 0.1236])
tensor([0.1953])
tensor(-1.)
140/500


100%|██████████| 10/10 [07:38<00:00, 45.81s/it]


Winners:  {1: 9, 0: 1}

Policy Loss 0.015821911705036957
Value Loss 1.0800095796585083
Examples:
tensor([0.1441, 0.1465, 0.1583, 0.1943, 0.1338, 0.1329, 0.1486])
tensor([0.1351, 0.1338, 0.1464, 0.1586, 0.1586, 0.1338, 0.1338])
tensor([0.1661])
tensor(-1.)

Policy Loss 0.015247846332689127
Value Loss 1.0425628920396168
Examples:
tensor([0.1539, 0.1491, 0.1671, 0.1580, 0.1109, 0.1218, 0.1505])
tensor([0.1353, 0.1422, 0.1572, 0.1525, 0.1394, 0.1380, 0.1353])
tensor([0.1437])
tensor(-1.)
141/500


100%|██████████| 10/10 [08:34<00:00, 51.40s/it]


Winners:  {1: 8, 0: 2}

Policy Loss 0.026914367452263832
Value Loss 0.8267419934272766
Examples:
tensor([0.1225, 0.1378, 0.1353, 0.1675, 0.1343, 0.1196, 0.1259])
tensor([0.1682, 0.1448, 0.1419, 0.1507, 0.1284, 0.1323, 0.1337])
tensor([-0.1311])
tensor(1.)

Policy Loss 0.028265942508975666
Value Loss 0.7767511308193207
Examples:
tensor([0.1412, 0.1298, 0.1846, 0.1731, 0.1570, 0.1635, 0.1245])
tensor([0.1172, 0.1172, 0.1172, 0.1172, 0.1172, 0.2970, 0.1172])
tensor([0.1602])
tensor(-1.)
142/500


100%|██████████| 10/10 [06:45<00:00, 40.52s/it]


Winners:  {1: 4, 0: 6}

Policy Loss 0.015828713464240234
Value Loss 1.0654770533243816
Examples:
tensor([0.1140, 0.1262, 0.1242, 0.1681, 0.1730, 0.1083, 0.1213])
tensor([0.1224, 0.1224, 0.1224, 0.1326, 0.2440, 0.1339, 0.1224])
tensor([0.0651])
tensor(1.)

Policy Loss 0.014981579345961412
Value Loss 1.0369831522305806
Examples:
tensor([0.1604, 0.1635, 0.1551, 0.1550, 0.1517, 0.0985, 0.1679])
tensor([0.1501, 0.1486, 0.1501, 0.1501, 0.1562, 0.0000, 0.2450])
tensor([0.0229])
tensor(1.)
143/500


100%|██████████| 10/10 [07:15<00:00, 43.57s/it]


Winners:  {0: 3, 1: 7}

Policy Loss 0.013509511016309261
Value Loss 0.9874157309532166
Examples:
tensor([0.1363, 0.1193, 0.1186, 0.1550, 0.1560, 0.1263, 0.1192])
tensor([0.1172, 0.1172, 0.2970, 0.1172, 0.1172, 0.1172, 0.1172])
tensor([-0.0146])
tensor(1.)

Policy Loss 0.011593634262681007
Value Loss 0.9799723774194717
Examples:
tensor([0.1233, 0.1250, 0.1410, 0.1430, 0.1595, 0.1359, 0.1180])
tensor([0.1335, 0.1322, 0.1335, 0.1432, 0.1749, 0.1505, 0.1322])
tensor([0.0412])
tensor(1.)
144/500


100%|██████████| 10/10 [06:48<00:00, 40.86s/it]


Winners:  {0: 8, 1: 2}

Policy Loss 0.012480298057198524
Value Loss 1.030780017375946
Examples:
tensor([0.1068, 0.1270, 0.1381, 0.1485, 0.1668, 0.1330, 0.1238])
tensor([0.1364, 0.1377, 0.1734, 0.1391, 0.1337, 0.1419, 0.1377])
tensor([0.0077])
tensor(1.)

Policy Loss 0.011779847787693143
Value Loss 1.006464809179306
Examples:
tensor([0.1201, 0.1538, 0.1176, 0.1569, 0.1393, 0.1308, 0.1202])
tensor([0.1854, 0.1373, 0.1373, 0.1360, 0.1320, 0.1360, 0.1360])
tensor([-0.0047])
tensor(1.)
145/500


100%|██████████| 10/10 [08:00<00:00, 48.04s/it]


Winners:  {0: 3, 1: 7}

Policy Loss 0.010948138777166605
Value Loss 0.9854028224945068
Examples:
tensor([0.1515, 0.1594, 0.1381, 0.1638, 0.1349, 0.1408, 0.1262])
tensor([0.1345, 0.1319, 0.1428, 0.1332, 0.1871, 0.1372, 0.1332])
tensor([-0.0222])
tensor(1.)

Policy Loss 0.011490814154967666
Value Loss 0.9656885117292404
Examples:
tensor([0.1457, 0.1367, 0.1533, 0.1315, 0.1737, 0.1389, 0.1587])
tensor([0.1382, 0.1424, 0.1409, 0.1497, 0.1512, 0.1395, 0.1382])
tensor([0.0311])
tensor(-1.)
146/500


100%|██████████| 10/10 [08:52<00:00, 53.23s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.006347354967147112
Value Loss 0.9981691241264343
Examples:
tensor([0.1336, 0.1458, 0.1547, 0.1436, 0.1287, 0.1433, 0.1325])
tensor([0.1409, 0.1496, 0.1557, 0.1423, 0.1395, 0.1354, 0.1367])
tensor([-0.0651])
tensor(1.)

Policy Loss 0.007262423052452505
Value Loss 0.9911985993385315
Examples:
tensor([0.1573, 0.1584, 0.1493, 0.1374, 0.1367, 0.1470, 0.1275])
tensor([0.1336, 0.1716, 0.1492, 0.1419, 0.1336, 0.1363, 0.1336])
tensor([0.0645])
tensor(-1.)
147/500


100%|██████████| 10/10 [08:48<00:00, 52.82s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.008493639839192232
Value Loss 0.9607987999916077
Examples:
tensor([0.1366, 0.1380, 0.1796, 0.1322, 0.1405, 0.1354, 0.1362])
tensor([0.1367, 0.1480, 0.1604, 0.1422, 0.1380, 0.1380, 0.1367])
tensor([0.1117])
tensor(-1.)

Policy Loss 0.008236191468313336
Value Loss 0.9368282159169515
Examples:
tensor([0.1646, 0.1589, 0.1957, 0.1563, 0.1843, 0.1675, 0.1421])
tensor([0.1365, 0.1351, 0.1406, 0.1684, 0.1464, 0.1406, 0.1324])
tensor([0.0318])
tensor(1.)
148/500


100%|██████████| 10/10 [08:36<00:00, 51.64s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.014515532180666924
Value Loss 0.8414490818977356
Examples:
tensor([0.1371, 0.1342, 0.1358, 0.1548, 0.1379, 0.1471, 0.1207])
tensor([0.1493, 0.1479, 0.0000, 0.1479, 0.2563, 0.1493, 0.1493])
tensor([0.0647])
tensor(1.)

Policy Loss 0.01336430013179779
Value Loss 0.8123772641023
Examples:
tensor([0.1340, 0.1630, 0.1411, 0.1392, 0.1686, 0.1439, 0.1445])
tensor([0.1423, 0.1423, 0.1395, 0.1588, 0.1381, 0.1395, 0.1395])
tensor([-0.3327])
tensor(-1.)
149/500


100%|██████████| 10/10 [07:53<00:00, 47.34s/it]


Winners:  {1: 8, 0: 2}

Policy Loss 0.016655656043440104
Value Loss 1.0071201026439667
Examples:
tensor([0.1510, 0.1363, 0.1556, 0.1459, 0.1895, 0.1434, 0.1261])
tensor([0.1264, 0.1303, 0.1397, 0.1529, 0.1886, 0.1356, 0.1264])
tensor([0.2157])
tensor(1.)

Policy Loss 0.016293107997626066
Value Loss 0.9610380977392197
Examples:
tensor([0.1079, 0.1206, 0.1350, 0.1493, 0.1018, 0.1405, 0.0849])
tensor([0.2714, 0.1460, 0.1446, 0.1453, 0.0000, 0.1467, 0.1460])
tensor([0.1586])
tensor(-1.)
150/500


100%|██████████| 10/10 [07:47<00:00, 46.79s/it]


Winners:  {0: 4, 1: 6}

Policy Loss 0.013727342709898949
Value Loss 1.0023727615674336
Examples:
tensor([0.1345, 0.1197, 0.1335, 0.1725, 0.1725, 0.1457, 0.1493])
tensor([0.1344, 0.1331, 0.1371, 0.1358, 0.1907, 0.1358, 0.1331])
tensor([0.1946])
tensor(-1.)

Policy Loss 0.017902630070845287
Value Loss 1.0174503823121388
Examples:
tensor([0.1144, 0.1267, 0.1047, 0.1833, 0.1698, 0.1193, 0.1261])
tensor([0.1186, 0.1210, 0.1210, 0.2802, 0.1210, 0.1186, 0.1198])
tensor([0.1789])
tensor(-1.)
151/500


100%|██████████| 10/10 [17:05<00:00, 102.55s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.013141624939938387
Value Loss 0.8485632936159769
Examples:
tensor([0.1507, 0.1314, 0.1476, 0.1754, 0.1739, 0.1608, 0.1423])
tensor([0.1353, 0.1387, 0.1495, 0.1572, 0.1473, 0.1353, 0.1367])
tensor([0.2484])
tensor(1.)

Policy Loss 0.012709111906588078
Value Loss 0.8122492929299673
Examples:
tensor([0.1475, 0.1365, 0.1654, 0.1872, 0.1651, 0.1390, 0.1278])
tensor([0.1291, 0.1317, 0.1371, 0.1561, 0.1851, 0.1304, 0.1304])
tensor([-0.0573])
tensor(-1.)
152/500


100%|██████████| 10/10 [19:15<00:00, 115.53s/it] 


Winners:  {1: 8, 0: 2}

Policy Loss 0.011599168802301088
Value Loss 0.9631389180819193
Examples:
tensor([0.1212, 0.1516, 0.1323, 0.1567, 0.1841, 0.1292, 0.1179])
tensor([0.1194, 0.1206, 0.1194, 0.2684, 0.1333, 0.1194, 0.1194])
tensor([-0.1282])
tensor(-1.)

Policy Loss 0.01167029639085134
Value Loss 0.9121354420979818
Examples:
tensor([0.1189, 0.1084, 0.1617, 0.1448, 0.1191, 0.1366, 0.1454])
tensor([0.1301, 0.1341, 0.1347, 0.2113, 0.1256, 0.1301, 0.1341])
tensor([-0.3389])
tensor(-1.)
153/500


100%|██████████| 10/10 [08:16<00:00, 49.63s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.012082520561913649
Value Loss 1.0201522707939148
Examples:
tensor([0.1299, 0.1523, 0.1289, 0.1511, 0.1654, 0.1415, 0.1354])
tensor([0.1231, 0.1269, 0.1231, 0.2312, 0.1231, 0.1445, 0.1281])
tensor([-0.1261])
tensor(1.)

Policy Loss 0.012023464310914278
Value Loss 0.9646661480267843
Examples:
tensor([0.1515, 0.1746, 0.1968, 0.1451, 0.1758, 0.1375, 0.1246])
tensor([0.1620, 0.1790, 0.1503, 0.0000, 0.1746, 0.1737, 0.1604])
tensor([-0.0607])
tensor(-1.)
154/500


100%|██████████| 10/10 [07:17<00:00, 43.73s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.01849892269819975
Value Loss 0.9417194426059723
Examples:
tensor([0.1160, 0.1370, 0.1561, 0.1641, 0.0889, 0.1352, 0.1232])
tensor([0.1609, 0.0000, 0.1609, 0.2587, 0.0000, 0.2587, 0.1609])
tensor([0.2420])
tensor(-1.)

Policy Loss 0.016657118452712893
Value Loss 0.9064538180828094
Examples:
tensor([0.1542, 0.1240, 0.1309, 0.1689, 0.1553, 0.1591, 0.1499])
tensor([0.1203, 0.1240, 0.1203, 0.1215, 0.2732, 0.1203, 0.1203])
tensor([0.3454])
tensor(1.)
155/500


100%|██████████| 10/10 [07:49<00:00, 46.94s/it]


Winners:  {0: 4, 1: 6}

Policy Loss 0.014345887117087841
Value Loss 1.006795883178711
Examples:
tensor([0.1232, 0.1107, 0.1355, 0.1813, 0.1463, 0.1210, 0.1324])
tensor([0.1228, 0.1266, 0.2376, 0.1344, 0.1304, 0.1241, 0.1241])
tensor([0.3736])
tensor(-1.)

Policy Loss 0.014394833240658045
Value Loss 0.9936453253030777
Examples:
tensor([0.1031, 0.1118, 0.1194, 0.1689, 0.1259, 0.1154, 0.1189])
tensor([0.1229, 0.1241, 0.1414, 0.2130, 0.1400, 0.1345, 0.1241])
tensor([0.3416])
tensor(1.)
156/500


100%|██████████| 10/10 [07:47<00:00, 46.72s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.01849650451913476
Value Loss 0.9420567750930786
Examples:
tensor([0.1413, 0.1285, 0.1282, 0.1231, 0.1538, 0.1641, 0.1544])
tensor([0.1210, 0.1210, 0.1210, 0.1291, 0.2640, 0.1228, 0.1210])
tensor([0.0515])
tensor(-1.)

Policy Loss 0.018035861430689692
Value Loss 0.9252354651689529
Examples:
tensor([0.1261, 0.1367, 0.1459, 0.1432, 0.1423, 0.1348, 0.1419])
tensor([0.1357, 0.3175, 0.1371, 0.0000, 0.1357, 0.1384, 0.1357])
tensor([0.2791])
tensor(1.)
157/500


100%|██████████| 10/10 [07:38<00:00, 45.90s/it]


Winners:  {0: 3, 1: 7}

Policy Loss 0.01970602758228779
Value Loss 0.980948269367218
Examples:
tensor([0.1221, 0.1308, 0.1731, 0.1532, 0.1759, 0.1386, 0.1328])
tensor([0.1194, 0.1194, 0.2849, 0.1188, 0.1194, 0.1194, 0.1188])
tensor([0.0622])
tensor(-1.)

Policy Loss 0.019900226034224033
Value Loss 0.959016427397728
Examples:
tensor([0.0933, 0.1295, 0.1542, 0.1814, 0.1508, 0.1023, 0.1296])
tensor([0.1339, 0.1604, 0.1394, 0.1367, 0.1422, 0.1408, 0.1466])
tensor([0.0368])
tensor(1.)
158/500


100%|██████████| 10/10 [07:48<00:00, 46.82s/it]


Winners:  {0: 3, 1: 7}

Policy Loss 0.009599957149475813
Value Loss 0.894495040178299
Examples:
tensor([0.1120, 0.1287, 0.1370, 0.1750, 0.1366, 0.1295, 0.1093])
tensor([0.1246, 0.1246, 0.2484, 0.1310, 0.1246, 0.1234, 0.1234])
tensor([0.1361])
tensor(1.)

Policy Loss 0.010850241873413324
Value Loss 0.8939479440450668
Examples:
tensor([0.1471, 0.1392, 0.1673, 0.1826, 0.1382, 0.1381, 0.1407])
tensor([0.1266, 0.1266, 0.1762, 0.1610, 0.1457, 0.1372, 0.1266])
tensor([0.2475])
tensor(1.)
159/500


100%|██████████| 10/10 [06:48<00:00, 40.83s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.009397828485816717
Value Loss 0.8986400663852692
Examples:
tensor([0.1336, 0.1396, 0.1639, 0.1818, 0.1211, 0.1232, 0.1407])
tensor([0.1295, 0.1295, 0.1504, 0.1748, 0.1460, 0.1417, 0.1282])
tensor([0.1131])
tensor(1.)

Policy Loss 0.008940124418586493
Value Loss 0.8722911030054092
Examples:
tensor([0.1393, 0.1105, 0.1792, 0.1931, 0.1375, 0.1546, 0.1505])
tensor([0.1423, 0.1437, 0.1409, 0.1588, 0.1381, 0.1381, 0.1381])
tensor([0.0670])
tensor(-1.)
160/500


100%|██████████| 10/10 [07:13<00:00, 43.30s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.012085657101124525
Value Loss 0.9000696539878845
Examples:
tensor([0.1467, 0.1464, 0.1595, 0.1938, 0.1800, 0.1422, 0.1435])
tensor([0.1277, 0.1383, 0.1514, 0.1886, 0.1411, 0.1264, 0.1264])
tensor([0.2586])
tensor(1.)

Policy Loss 0.011235857848078012
Value Loss 0.8768680393695831
Examples:
tensor([0.1448, 0.1589, 0.0991, 0.1860, 0.1613, 0.1328, 0.1146])
tensor([0.1757, 0.1672, 0.0000, 0.1655, 0.1638, 0.1606, 0.1672])
tensor([0.2081])
tensor(-1.)
161/500


100%|██████████| 10/10 [07:41<00:00, 46.13s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.019710015505552292
Value Loss 0.9820718367894491
Examples:
tensor([0.1287, 0.1257, 0.1258, 0.1418, 0.1409, 0.1416, 0.1268])
tensor([0.1330, 0.1317, 0.1310, 0.1330, 0.1317, 0.1330, 0.2065])
tensor([0.1376])
tensor(1.)

Policy Loss 0.02099606115370989
Value Loss 0.9783596098423004
Examples:
tensor([0.1212, 0.1404, 0.1568, 0.1427, 0.1826, 0.1573, 0.1513])
tensor([0.1603, 0.1436, 0.1436, 0.1353, 0.1313, 0.1436, 0.1422])
tensor([-0.0840])
tensor(-1.)
162/500


100%|██████████| 10/10 [07:08<00:00, 42.89s/it]


Winners:  {0: 4, 1: 6}

Policy Loss 0.017438406590372324
Value Loss 0.9192319810390472
Examples:
tensor([0.1347, 0.1134, 0.1450, 0.1782, 0.1440, 0.1422, 0.1287])
tensor([0.1524, 0.1248, 0.1571, 0.1261, 0.1900, 0.1248, 0.1248])
tensor([-0.1133])
tensor(-1.)

Policy Loss 0.01737250667065382
Value Loss 0.8579846918582916
Examples:
tensor([0.1971, 0.1461, 0.1883, 0.1756, 0.1575, 0.1857, 0.1395])
tensor([0.2018, 0.1353, 0.1339, 0.1353, 0.1287, 0.1326, 0.1326])
tensor([0.1437])
tensor(1.)
163/500


100%|██████████| 10/10 [09:03<00:00, 54.39s/it]


Winners:  {1: 4, 0: 6}

Policy Loss 0.02015336665014426
Value Loss 1.0780963500340779
Examples:
tensor([0.1761, 0.1089, 0.1571, 0.1393, 0.1418, 0.1772, 0.0941])
tensor([0.1174, 0.1186, 0.1174, 0.2945, 0.1174, 0.1174, 0.1174])
tensor([0.1334])
tensor(-1.)

Policy Loss 0.017656216553101938
Value Loss 1.0314139525095622
Examples:
tensor([0.1224, 0.1348, 0.1352, 0.1181, 0.1019, 0.1041, 0.1230])
tensor([0.1194, 0.2849, 0.1194, 0.1194, 0.1194, 0.1182, 0.1194])
tensor([-0.0778])
tensor(1.)
164/500


100%|██████████| 10/10 [05:57<00:00, 35.75s/it]


Winners:  {1: 5, 0: 5}

Policy Loss 0.014707405120134354
Value Loss 1.145285964012146
Examples:
tensor([0.0507, 0.1241, 0.0859, 0.1069, 0.0741, 0.0757, 0.0914])
tensor([0.1389, 0.2222, 0.1389, 0.1389, 0.1389, 0.2222, 0.0000])
tensor([0.0498])
tensor(1.)

Policy Loss 0.014511295594274998
Value Loss 1.0945596396923065
Examples:
tensor([0.1427, 0.1489, 0.1619, 0.1469, 0.1316, 0.1550, 0.1279])
tensor([0.1242, 0.1248, 0.2539, 0.1224, 0.1212, 0.1274, 0.1261])
tensor([-0.0838])
tensor(-1.)
165/500


100%|██████████| 10/10 [07:31<00:00, 45.17s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.018724684603512287
Value Loss 1.1605286002159119
Examples:
tensor([0.1731, 0.1733, 0.1874, 0.1707, 0.1566, 0.1524, 0.1219])
tensor([0.1888, 0.1291, 0.1344, 0.1456, 0.1291, 0.1317, 0.1413])
tensor([-0.1900])
tensor(1.)

Policy Loss 0.01579312840476632
Value Loss 1.1175515353679657
Examples:
tensor([0.1166, 0.1329, 0.1240, 0.1409, 0.0942, 0.0951, 0.1158])
tensor([0.1238, 0.1226, 0.1263, 0.2595, 0.1226, 0.1226, 0.1226])
tensor([-0.0826])
tensor(1.)
166/500


100%|██████████| 10/10 [07:07<00:00, 42.72s/it]


Winners:  {1: 5, 0: 5}

Policy Loss 0.014171430841088295
Value Loss 0.9900436699390411
Examples:
tensor([0.1270, 0.1499, 0.1369, 0.1484, 0.1087, 0.1027, 0.1201])
tensor([0.1523, 0.1478, 0.1617, 0.1449, 0.1351, 0.1272, 0.1311])
tensor([-0.0140])
tensor(-1.)

Policy Loss 0.013362472876906395
Value Loss 0.9767809510231018
Examples:
tensor([0.1714, 0.1843, 0.1690, 0.1454, 0.1453, 0.1583, 0.1198])
tensor([0.1356, 0.1924, 0.1440, 0.1397, 0.1277, 0.1316, 0.1290])
tensor([0.2433])
tensor(1.)
167/500


100%|██████████| 10/10 [05:17<00:00, 31.76s/it]


Winners:  {0: 6, 1: 4}

Policy Loss 0.01043214276432991
Value Loss 0.9707289040088654
Examples:
tensor([0.1560, 0.1510, 0.1741, 0.1397, 0.1400, 0.1411, 0.1221])
tensor([0.1937, 0.1223, 0.1235, 0.1223, 0.1937, 0.1223, 0.1223])
tensor([0.1412])
tensor(1.)

Policy Loss 0.00941174104809761
Value Loss 0.9481868743896484
Examples:
tensor([0.1494, 0.1337, 0.1420, 0.1350, 0.1472, 0.1479, 0.1482])
tensor([0.2697, 0.1212, 0.1243, 0.1212, 0.1212, 0.1212, 0.1212])
tensor([-0.0453])
tensor(-1.)
168/500


100%|██████████| 10/10 [06:14<00:00, 37.50s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.012797480449080467
Value Loss 0.9607424437999725
Examples:
tensor([0.1255, 0.1534, 0.1538, 0.1445, 0.1242, 0.1166, 0.1253])
tensor([0.1377, 0.2054, 0.1297, 0.1419, 0.1297, 0.1284, 0.1271])
tensor([-0.0008])
tensor(1.)

Policy Loss 0.011880273232236505
Value Loss 0.9548293799161911
Examples:
tensor([0.1401, 0.1712, 0.1662, 0.1632, 0.1569, 0.1412, 0.1218])
tensor([0.1294, 0.1243, 0.1243, 0.2528, 0.1231, 0.1231, 0.1231])
tensor([0.1726])
tensor(1.)
169/500


100%|██████████| 10/10 [08:47<00:00, 52.72s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.010111928296585878
Value Loss 0.9552024801572164
Examples:
tensor([0.1307, 0.1389, 0.1547, 0.1425, 0.1234, 0.1151, 0.1315])
tensor([0.1246, 0.1363, 0.2293, 0.1336, 0.1271, 0.1246, 0.1246])
tensor([-0.2099])
tensor(-1.)

Policy Loss 0.012259702353427807
Value Loss 0.9228908816973368
Examples:
tensor([0.1730, 0.1485, 0.1842, 0.1355, 0.1614, 0.1283, 0.1448])
tensor([0.1256, 0.1361, 0.1417, 0.2092, 0.1361, 0.1256, 0.1256])
tensor([-0.0682])
tensor(1.)
170/500


100%|██████████| 10/10 [07:14<00:00, 43.47s/it]


Winners:  {1: 7, 0: 3}

Policy Loss 0.009140410926192999
Value Loss 0.9441589117050171
Examples:
tensor([0.1490, 0.1489, 0.1771, 0.1409, 0.1509, 0.1306, 0.1490])
tensor([0.1224, 0.1224, 0.2618, 0.1261, 0.1224, 0.1224, 0.1224])
tensor([-0.3488])
tensor(1.)

Policy Loss 0.009738471359014511
Value Loss 0.955037385225296
Examples:
tensor([0.1430, 0.1295, 0.1444, 0.1389, 0.1475, 0.1364, 0.1199])
tensor([0.1217, 0.1205, 0.2709, 0.1217, 0.1217, 0.1217, 0.1217])
tensor([0.1099])
tensor(-1.)
171/500


100%|██████████| 10/10 [07:22<00:00, 44.24s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.01696829777210951
Value Loss 1.1065322756767273
Examples:
tensor([0.1386, 0.1392, 0.1667, 0.1538, 0.1335, 0.1278, 0.1271])
tensor([0.1363, 0.1462, 0.1733, 0.1297, 0.1377, 0.1377, 0.1391])
tensor([0.1348])
tensor(1.)

Policy Loss 0.01667330926284194
Value Loss 1.0739883482456207
Examples:
tensor([0.1282, 0.1259, 0.1418, 0.1646, 0.1289, 0.1024, 0.1143])
tensor([0.1261, 0.1882, 0.1636, 0.1436, 0.1287, 0.1249, 0.1249])
tensor([-0.0730])
tensor(1.)
172/500


100%|██████████| 10/10 [08:20<00:00, 50.01s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.014192701317369938
Value Loss 0.853596568107605
Examples:
tensor([0.1504, 0.1619, 0.1662, 0.1736, 0.1691, 0.1288, 0.1486])
tensor([0.1362, 0.1476, 0.1362, 0.1362, 0.1767, 0.1335, 0.1335])
tensor([-0.3308])
tensor(-1.)

Policy Loss 0.013066555683811506
Value Loss 0.8259243865807852
Examples:
tensor([0.1240, 0.1464, 0.1528, 0.1550, 0.1491, 0.1295, 0.1400])
tensor([0.1349, 0.1362, 0.1506, 0.1749, 0.1349, 0.1349, 0.1336])
tensor([0.1821])
tensor(1.)
173/500


100%|██████████| 10/10 [07:20<00:00, 44.08s/it]


Winners:  {1: 5, 0: 5}

Policy Loss 0.011755488812923431
Value Loss 0.9403426051139832
Examples:
tensor([0.1230, 0.1450, 0.1598, 0.1539, 0.1446, 0.1361, 0.1308])
tensor([0.1343, 0.1343, 0.1350, 0.1935, 0.1343, 0.1343, 0.1343])
tensor([0.1091])
tensor(-1.)

Policy Loss 0.01238298648968339
Value Loss 0.8833298683166504
Examples:
tensor([0.1408, 0.1461, 0.1643, 0.1663, 0.1574, 0.1322, 0.1365])
tensor([0.1249, 0.1287, 0.1978, 0.1466, 0.1340, 0.1380, 0.1300])
tensor([0.0946])
tensor(1.)
174/500


100%|██████████| 10/10 [06:31<00:00, 39.11s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.008823075331747532
Value Loss 1.0458645820617676
Examples:
tensor([0.1297, 0.1321, 0.1651, 0.1973, 0.1444, 0.1252, 0.1212])
tensor([0.1233, 0.1245, 0.1233, 0.2246, 0.1552, 0.1258, 0.1233])
tensor([0.1206])
tensor(-1.)

Policy Loss 0.0108056899625808
Value Loss 1.048169881105423
Examples:
tensor([0.1035, 0.1385, 0.1226, 0.2067, 0.1338, 0.1250, 0.1240])
tensor([0.1207, 0.1219, 0.1231, 0.2686, 0.1244, 0.1207, 0.1207])
tensor([-0.3675])
tensor(-1.)
175/500


100%|██████████| 10/10 [07:07<00:00, 42.70s/it]


Winners:  {1: 6, 0: 4}

Policy Loss 0.015841062180697918
Value Loss 0.9613150358200073
Examples:
tensor([0.1342, 0.1402, 0.1407, 0.1893, 0.1386, 0.1306, 0.1203])
tensor([0.1224, 0.1249, 0.1394, 0.2208, 0.1465, 0.1236, 0.1224])
tensor([0.1864])
tensor(-1.)

Policy Loss 0.015069525921717286
Value Loss 0.935565784573555
Examples:
tensor([0.1273, 0.1452, 0.1515, 0.1751, 0.1493, 0.1441, 0.1448])
tensor([0.1407, 0.1400, 0.1660, 0.1380, 0.1352, 0.1407, 0.1393])
tensor([-0.2134])
tensor(-1.)
176/500


100%|██████████| 10/10 [07:19<00:00, 43.90s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.010610090103000402
Value Loss 0.9543608129024506
Examples:
tensor([0.1286, 0.1392, 0.1607, 0.1790, 0.1499, 0.1397, 0.1280])
tensor([0.1220, 0.1257, 0.1403, 0.2291, 0.1376, 0.1232, 0.1220])
tensor([0.1734])
tensor(-1.)

Policy Loss 0.011059079086408019
Value Loss 0.9081194698810577
Examples:
tensor([0.1478, 0.1503, 0.1638, 0.1317, 0.1534, 0.1510, 0.1282])
tensor([0.1181, 0.2861, 0.1181, 0.1181, 0.1235, 0.1181, 0.1181])
tensor([0.0921])
tensor(1.)
177/500


100%|██████████| 10/10 [08:02<00:00, 48.23s/it]


Winners:  {0: 7, 1: 3}

Policy Loss 0.014285931829363108
Value Loss 1.2134159207344055
Examples:
tensor([0.1370, 0.1667, 0.1721, 0.1578, 0.1384, 0.1295, 0.1256])
tensor([0.1265, 0.1265, 0.2399, 0.1277, 0.1290, 0.1252, 0.1252])
tensor([-0.2188])
tensor(1.)

Policy Loss 0.01325770141556859
Value Loss 1.1154117733240128
Examples:
tensor([0.1051, 0.1454, 0.1330, 0.1488, 0.1139, 0.1020, 0.1104])
tensor([0.1257, 0.1992, 0.1418, 0.1598, 0.1245, 0.1245, 0.1245])
tensor([-0.0846])
tensor(1.)
178/500


100%|██████████| 10/10 [08:09<00:00, 48.98s/it]


Winners:  {0: 5, 1: 5}

Policy Loss 0.009784264490008354
Value Loss 0.9784755706787109
Examples:
tensor([0.1230, 0.1330, 0.1513, 0.1747, 0.1368, 0.1250, 0.1281])
tensor([0.1200, 0.1200, 0.1212, 0.2779, 0.1212, 0.1200, 0.1200])
tensor([-0.1671])
tensor(-1.)

Policy Loss 0.009813219541683793
Value Loss 0.9635296016931534
Examples:
tensor([0.1356, 0.1387, 0.1615, 0.1776, 0.1442, 0.1337, 0.1318])
tensor([0.1173, 0.1173, 0.1179, 0.2958, 0.1173, 0.1173, 0.1173])
tensor([0.1694])
tensor(-1.)
179/500


100%|██████████| 10/10 [09:27<00:00, 56.74s/it]


Winners:  {0: 4, 1: 6}

Policy Loss 0.011840383522212505
Value Loss 0.858060896396637
Examples:
tensor([0.1334, 0.1527, 0.1748, 0.1695, 0.1610, 0.1279, 0.1210])
tensor([0.1336, 0.1419, 0.1419, 0.1699, 0.1507, 0.1350, 0.1271])
tensor([0.1572])
tensor(1.)

Policy Loss 0.012683235729734102
Value Loss 0.8391767839590708
Examples:
tensor([0.1542, 0.1466, 0.1754, 0.1456, 0.1828, 0.1204, 0.1229])
tensor([0.1181, 0.1175, 0.2933, 0.1187, 0.1175, 0.1175, 0.1175])
tensor([0.3323])
tensor(1.)
180/500


  0%|          | 0/10 [00:00<?, ?it/s]