In [3]:
%load_ext autoreload
%autoreload 2

import torch
from alpha_connect import (
    AlphaZeroModelConnect4,
    Trainer,
    AlphaZeroModelChineseCheckers,
    GameChoice,
    AlphaZeroModelBounce,
)
import os
from game import BounceState

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
device = torch.device("mps")

args = {
    "batch_size": 128,
    "numIters": 500,  # Total number of training iterations
    "num_simulations": 500,  # Total number of MCTS simulations to run when deciding on a move to play
    "max_game_length": 200,  # Maximum number of moves in a game (used to avoid infinite games)
    "numEps": 70,  # Number of full games (episodes) to run during each iteration for each thread
    "numThreads": 1,  # Number of threads running simulations
    "numItersForTrainExamplesHistory": 20,
    "epochs": 3,  # Number of epochs of training per iteration
    "checkpoint_path": "../data/latest_bounce.pth",  # location to save latest set of weights
    "loss_history_path": "../data/loss_history_bounce.csv",  # location to save loss history
    "lr": 0.0005,  # learning rate
    "lr_decay": 0.995,  # learning rate decay
    "temperature": 1,  #
}

GameChoice.set_game(BounceState)

model = AlphaZeroModelBounce()
if os.path.exists(args["checkpoint_path"]):
    model.load_state_dict(torch.load(args["checkpoint_path"]))
    print("Loaded model from checkpoint")

model.to(device)

trainer = Trainer(model, args)
trainer.learn()

Loaded model from checkpoint
Resuming training from iteration 173 with best loss 1.1896456206838288
173/500 with lr 0.0004975



(Game length:21): 100%|██████████| 70/70 [28:00<00:00, 24.00s/it]



Loss: 1.481891137858232
Policy Loss 0.6339475736021996
Value Loss 0.8479435642560323
6 batches processed
Examples:
tensor([0.0117, 0.1204, 0.8679, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([0.0140, 0.9459, 0.0401, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0


(Game length:30): 100%|██████████| 70/70 [30:20<00:00, 26.01s/it]



Loss: 1.524160417417685
Policy Loss 0.6586818918585777
Value Loss 0.8654785255591074
6 batches processed
Examples:
tensor([0.0308, 0.0353, 0.0351, 0.0341, 0.0304, 0.0340, 0.0345, 0.0338, 0.0335,
        0.0357, 0.0339, 0.0297, 0.0313, 0.0306, 0.0329, 0.0315, 0.0374, 0.0329,
        0.0305, 0.0365, 0.0390, 0.0321, 0.0294, 0.0341, 0.0364, 0.0296, 0.0346,
        0.0364, 0.0290, 0.0349, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([0.0000, 0.0040, 0.9820, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0040, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0060, 0.0000,
        0.0000, 0.0000, 0.0040, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0


(Game length:20): 100%|██████████| 70/70 [29:15<00:00, 25.08s/it]



Loss: 1.4943298920989037
Policy Loss 0.6687054261565208
Value Loss 0.8256244659423828
6 batches processed
Examples:
tensor([0.0401, 0.0321, 0.0541, 0.0401, 0.0319, 0.0537, 0.0453, 0.0448, 0.0478,
        0.0361, 0.0523, 0.0497, 0.0379, 0.0440, 0.0418, 0.0501, 0.0540, 0.0419,
        0.0532, 0.0541, 0.0412, 0.0537, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([0.0020, 0.0080, 0.1283, 0.0160, 0.0341, 0.0842, 0.0301, 0.0160, 0.0140,
        0.0160, 0.2525, 0.0200, 0.0040, 0.1323, 0.0180, 0.0721, 0.0140, 0.0080,
        0.0501, 0.0601, 0.0080, 0.0120, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
  


(Game length:39): 100%|██████████| 70/70 [32:06<00:00, 27.52s/it]



Loss: 1.5735285952687263
Policy Loss 0.6610938683152199
Value Loss 0.9124347269535065
6 batches processed
Examples:
tensor([0.0371, 0.0383, 0.0294, 0.0322, 0.0367, 0.0307, 0.0325, 0.0302, 0.0317,
        0.0355, 0.0372, 0.0329, 0.0377, 0.0293, 0.0316, 0.0364, 0.0306, 0.0325,
        0.0297, 0.0313, 0.0361, 0.0383, 0.0365, 0.0300, 0.0320, 0.0307, 0.0329,
        0.0362, 0.0310, 0.0330, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([0.0060, 0.0040, 0.1122, 0.0200, 0.1924, 0.0020, 0.0140, 0.0180, 0.0040,
        0.0281, 0.


(Game length:37): 100%|██████████| 70/70 [31:32<00:00, 27.04s/it]



Loss: 1.50985316435496
Policy Loss 0.5887322425842285
Value Loss 0.9211209217707316
6 batches processed
Examples:
tensor([0.3694, 0.0970, 0.3011, 0.2326, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000])
tensor([0.2866, 0.1924, 0.2445, 0.2766, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.00


(Game length:21): 100%|██████████| 70/70 [27:11<00:00, 23.30s/it]



Loss: 1.398202359676361
Policy Loss 0.5077466726303101
Value Loss 0.890455687046051
5 batches processed
Examples:
tensor([0.6857, 0.3143, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([0.5451, 0.4549, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.00


(Game length:59): 100%|██████████| 70/70 [34:40<00:00, 29.72s/it]



Loss: 1.4749808882673583
Policy Loss 0.5726494863629341
Value Loss 0.9023314019044241
6 batches processed
Examples:
tensor([0.0284, 0.0231, 0.0267, 0.0287, 0.0230, 0.0264, 0.0268, 0.0205, 0.0249,
        0.0278, 0.0276, 0.0304, 0.0258, 0.0198, 0.0252, 0.0250, 0.0281, 0.0284,
        0.0236, 0.0276, 0.0201, 0.0217, 0.0298, 0.0271, 0.0224, 0.0283, 0.0257,
        0.0199, 0.0255, 0.0251, 0.0281, 0.0288, 0.0233, 0.0278, 0.0203, 0.0301,
        0.0271, 0.0229, 0.0279, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000])
tensor([0.0240, 0.0521, 0.0301, 0.0902, 0.0281, 0.0200, 0.0401, 0.0120, 0.0240,
        0.0621, 0.0140, 0.0220, 0.0120, 0.0080, 0.0461, 0.0040, 0.0441, 0.0220,
        0.0020, 0.0120, 0.0140, 0.0100, 0.0100, 0.0200, 0.0120, 0.0100, 0.0060,
        0.0040, 0.0100, 0.0561, 0.0220, 0.0361, 0.0020, 0.0641, 0.


(Game length:39): 100%|██████████| 70/70 [30:06<00:00, 25.80s/it]



Loss: 1.5036077722907066
Policy Loss 0.5822706148028374
Value Loss 0.9213371574878693
6 batches processed
Examples:
tensor([0.0339, 0.0398, 0.0485, 0.0345, 0.0401, 0.0484, 0.0363, 0.0303, 0.0371,
        0.0381, 0.0379, 0.0359, 0.0293, 0.0358, 0.0325, 0.0383, 0.0293, 0.0384,
        0.0311, 0.0309, 0.0358, 0.0295, 0.0353, 0.0326, 0.0388, 0.0393, 0.0303,
        0.0317, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([0.0721, 0.0120, 0.2024, 0.0220, 0.0160, 0.1142, 0.0160, 0.0040, 0.0421,
        0.0120, 0.0160, 0.0120, 0.0160, 0.0220, 0.0100, 0.0060, 0.0120, 0.0140,
        0.0020, 0.0080, 0.0441, 0.


(Game length:23): 100%|██████████| 70/70 [28:54<00:00, 24.78s/it]



Loss: 1.4449424942334494
Policy Loss 0.5913538336753845
Value Loss 0.8535886605580648
6 batches processed
Examples:
tensor([0.0402, 0.0267, 0.0391, 0.0345, 0.0377, 0.0292, 0.0417, 0.0365, 0.0352,
        0.0363, 0.0294, 0.0384, 0.0350, 0.0323, 0.0416, 0.0405, 0.0336, 0.0372,
        0.0362, 0.0346, 0.0358, 0.0294, 0.0379, 0.0348, 0.0326, 0.0422, 0.0340,
        0.0373, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000])
tensor([0.0501, 0.0782, 0.0020, 0.0020, 0.0281, 0.0281, 0.0020, 0.0220, 0.1603,
        0.0100, 0.0782, 0.0361, 0.0301, 0.0160, 0.


(Game length:21): 100%|██████████| 70/70 [27:20<00:00, 23.43s/it]



Loss: 1.5172307267785072
Policy Loss 0.6393632665276527
Value Loss 0.8778674602508545
6 batches processed
Examples:
tensor([0.0373, 0.0320, 0.0348, 0.0263, 0.0359, 0.0304, 0.0281, 0.0340, 0.0372,
        0.0315, 0.0348, 0.0243, 0.0264, 0.0361, 0.0305, 0.0276, 0.0346, 0.0341,
        0.0262, 0.0291, 0.0287, 0.0341, 0.0341, 0.0262, 0.0294, 0.0289, 0.0345,
        0.0339, 0.0265, 0.0291, 0.0288, 0.0346, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000])
tensor([0.0301, 0.0240, 0.0140, 0.0060, 0.0120, 0.0060, 0.0601, 0.0160, 0.0080,
        0.0020, 0.0140, 0.0100, 0.0741, 0.2365, 0.0301, 0.0020, 0.0020, 0.0220,
        0.0301, 0.0100, 0.0020, 0.0281, 0.0020, 0.0020, 0.1583, 0.


(Game length:27): 100%|██████████| 70/70 [28:23<00:00, 24.34s/it]



Loss: 1.4562278936306634
Policy Loss 0.5370314568281174
Value Loss 0.9191964368025461
6 batches processed
Examples:
tensor([0.1162, 0.0674, 0.1314, 0.0651, 0.1046, 0.1054, 0.0401, 0.0508, 0.1084,
        0.1146, 0.0683, 0.0277, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([0.1443, 0.0180, 0.1222, 0.0020, 0.0060, 0.0982, 0.0100, 0.3046, 0.2144,
        0.0681, 0.0060, 0.0060, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.


(Game length:43): 100%|██████████| 70/70 [32:48<00:00, 28.12s/it]



Loss: 1.3627047315239906
Policy Loss 0.5168577507138252
Value Loss 0.8458469808101654
6 batches processed
Examples:
tensor([0.0903, 0.0962, 0.1013, 0.0893, 0.0851, 0.0767, 0.0759, 0.0776, 0.0719,
        0.0784, 0.0797, 0.0776, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000])
tensor([0.0381, 0.0220, 0.0381, 0.0301, 0.0321, 0.5611, 0.0220, 0.0160, 0.0301,
        0.0240, 0.0601, 0.1263, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.


(Game length:48): 100%|██████████| 70/70 [34:03<00:00, 29.19s/it]



Loss: 1.5599966123700142
Policy Loss 0.5747036412358284
Value Loss 0.9852929711341858
6 batches processed
Examples:
tensor([0.0387, 0.0315, 0.0424, 0.0388, 0.0464, 0.0306, 0.0450, 0.0358, 0.0384,
        0.0331, 0.0435, 0.0370, 0.0312, 0.0442, 0.0409, 0.0414, 0.0380, 0.0362,
        0.0415, 0.0484, 0.0378, 0.0469, 0.0479, 0.0371, 0.0474, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([0.0000, 0.0000, 0.0020, 0.0040, 0.0020, 0.0000, 0.0060, 0.9419, 0.0020,
        0.0000, 0.0040, 0.0040, 0.0000, 0.0060, 0.0040, 0.0060, 0.0020, 0.0000,
        0.0040, 0.0020, 0.0020, 0.0020, 0.0020, 0.0020, 0.0020, 0.0000, 0.0000,
        0.


(Game length:20): 100%|██████████| 70/70 [26:09<00:00, 22.42s/it]



Loss: 1.397652480006218
Policy Loss 0.45680759847164154
Value Loss 0.9408448815345765
5 batches processed
Examples:
tensor([0.0399, 0.0506, 0.0692, 0.0407, 0.0508, 0.0687, 0.0412, 0.0405, 0.0522,
        0.0517, 0.0464, 0.0496, 0.0489, 0.0426, 0.0387, 0.0441, 0.0367, 0.0304,
        0.0446, 0.0374, 0.0302, 0.0450, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([0.1403, 0.0200, 0.0641, 0.0240, 0.1002, 0.0641, 0.0361, 0.0240, 0.0481,
        0.0100, 0.0421, 0.0561, 0.0541, 0.0341, 0.0521, 0.0341, 0.0341, 0.0281,
        0.0401, 0.0361, 0.0200, 0.0381, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([-0.0253], grad_fn=<SelectBackward0>)
tensor(1.)
187/500 with lr 0.0004637


(Game length:24): 100%|██████████| 70/70 [28:53<00:00, 24.77s/it]



Loss: 1.3070518349607787
Policy Loss 0.44457045942544937
Value Loss 0.8624813755353292
6 batches processed
Examples:
tensor([0.0664, 0.0914, 0.0708, 0.0883, 0.0965, 0.0634, 0.0902, 0.0705, 0.0887,
        0.0896, 0.0936, 0.0907, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([0.0762, 0.0782, 0.0882, 0.0922, 0.0982, 0.1022, 0.1002, 0.0802, 0.0461,
        0.0721, 0.0902, 0.0762, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0


(Game length:39): 100%|██████████| 70/70 [30:10<00:00, 25.87s/it]



Loss: 1.4606667583187423
Policy Loss 0.5146907493472099
Value Loss 0.9459760089715322
6 batches processed
Examples:
tensor([0.0703, 0.0719, 0.0679, 0.0564, 0.0822, 0.0612, 0.0806, 0.0708, 0.0681,
        0.0753, 0.0741, 0.0498, 0.0602, 0.1113, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000])
tensor([0.0401, 0.0100, 0.0200, 0.0080, 0.0200, 0.0100, 0.0160, 0.0140, 0.0180,
        0.0281, 0.0040, 0.6273, 0.0160, 0.1683, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.


(Game length:36): 100%|██████████| 70/70 [29:38<00:00, 25.40s/it]



Loss: 1.3695955723524094
Policy Loss 0.5019865483045578
Value Loss 0.8676090240478516
6 batches processed
Examples:
tensor([0.0914, 0.0771, 0.1116, 0.1025, 0.0864, 0.0762, 0.0958, 0.1023, 0.0863,
        0.0745, 0.0959, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([0.1423, 0.1303, 0.1403, 0.1082, 0.1062, 0.0261, 0.0581, 0.0721, 0.0421,
        0.0962, 0.0782, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.


(Game length:18): 100%|██████████| 70/70 [25:19<00:00, 21.70s/it]



Loss: 1.4299931585788728
Policy Loss 0.5168351233005524
Value Loss 0.9131580352783203
5 batches processed
Examples:
tensor([0.0530, 0.0439, 0.0426, 0.0532, 0.0438, 0.0428, 0.0509, 0.0447, 0.0520,
        0.0317, 0.0550, 0.0429, 0.0354, 0.0430, 0.0430, 0.0451, 0.0488, 0.0463,
        0.0435, 0.0484, 0.0464, 0.0436, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([0.3026, 0.0261, 0.0301, 0.1022, 0.0040, 0.0421, 0.0401, 0.0140, 0.0020,
        0.0020, 0.0381, 0.0040, 0.0020, 0.0020, 0.0962, 0.0100, 0.0281, 0.0541,
        0.0120, 0.1263, 0.0421, 0.0200, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([-0.1181], grad_fn=<SelectBackward0>)
tensor(1.)
191/500 with lr 0.0004545781307912651



(Game length:34): 100%|██████████| 70/70 [30:18<00:00, 25.98s/it]



Loss: 1.3334438080588975
Policy Loss 0.4990721419453621
Value Loss 0.8343716661135355
6 batches processed
Examples:
tensor([0.0605, 0.0629, 0.0654, 0.0499, 0.0586, 0.0579, 0.0579, 0.0653, 0.0621,
        0.0641, 0.0497, 0.0585, 0.0584, 0.0570, 0.0679, 0.0538, 0.0500, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000])
tensor([0.0140, 0.7054, 0.0120, 0.1242, 0.0060, 0.0100, 0.0100, 0.0080, 0.0080,
        0.0120, 0.0160, 0.0100, 0.0140, 0.0100, 0.0140, 0.0180, 0.0080, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.


(Game length:30): 100%|██████████| 70/70 [30:13<00:00, 25.91s/it]



Loss: 1.444189546008905
Policy Loss 0.5501720383763313
Value Loss 0.8940175076325735
6 batches processed
Examples:
tensor([0.0269, 0.0268, 0.0290, 0.0264, 0.0245, 0.0334, 0.0274, 0.0303, 0.0314,
        0.0260, 0.0317, 0.0277, 0.0314, 0.0214, 0.0253, 0.0239, 0.0276, 0.0288,
        0.0271, 0.0269, 0.0291, 0.0265, 0.0245, 0.0334, 0.0272, 0.0305, 0.0313,
        0.0262, 0.0315, 0.0275, 0.0313, 0.0213, 0.0252, 0.0241, 0.0275, 0.0287,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000])
tensor([0.9198, 0.0020, 0.0020, 0.0000, 0.0000, 0.0020, 0.0000, 0.0040, 0.0080,
        0.0000, 0.0020, 0.0060, 0.0100, 0.0000, 0.0000, 0.0000, 0.0000, 0.0020,
        0.0000, 0.0040, 0.0020, 0.0000, 0.0000, 0.0080, 0.0000, 0.0140, 0.0020,
        0.0000, 0.0020, 0.0040, 0.0040, 0.0


(Game length:46): 100%|██████████| 70/70 [32:55<00:00, 28.22s/it]



Loss: 1.4315513471762338
Policy Loss 0.5194155275821686
Value Loss 0.9121358195940653
6 batches processed
Examples:
tensor([0.0714, 0.0840, 0.0815, 0.0595, 0.0921, 0.0790, 0.0836, 0.0571, 0.0911,
        0.0801, 0.0825, 0.0687, 0.0694, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([0.0140, 0.0381, 0.0381, 0.0060, 0.1162, 0.0100, 0.0180, 0.0020, 0.6112,
        0.0180, 0.0421, 0.0381, 0.0481, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.


(Game length:22): 100%|██████████| 70/70 [28:17<00:00, 24.25s/it]



Loss: 1.3911907076835632
Policy Loss 0.5276655852794647
Value Loss 0.8635251224040985
6 batches processed
Examples:
tensor([0.0169, 0.0223, 0.0165, 0.0148, 0.0188, 0.0195, 0.0197, 0.0137, 0.0159,
        0.0201, 0.0179, 0.0192, 0.0170, 0.0225, 0.0164, 0.0148, 0.0186, 0.0195,
        0.0197, 0.0138, 0.0159, 0.0202, 0.0178, 0.0192, 0.0171, 0.0231, 0.0164,
        0.0147, 0.0191, 0.0196, 0.0190, 0.0136, 0.0167, 0.0148, 0.0202, 0.0175,
        0.0183, 0.0185, 0.0174, 0.0237, 0.0169, 0.0147, 0.0188, 0.0192, 0.0194,
        0.0139, 0.0169, 0.0148, 0.0168, 0.0203, 0.0172, 0.0180, 0.0188, 0.0179,
        0.0185, 0.0174, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([0.0281, 0.0020, 0.0301, 0.0020, 0.0100, 0.0080, 0.0060, 0.0160, 0.0341,
        0.0100, 0.0020, 0.0140, 0.0120, 0.0160, 0.0020, 0.0721, 0.0060, 0.0080,
        0.0641, 0.0040, 0.0080, 0.0160, 0.0160, 0.0040, 0.0080, 0.0080, 0.0080,
        0.0060, 0.0060, 0.0140, 0.0200, 0.0080, 0.0040, 0.0140, 0.0621, 0.0040,
        0.


(Game length:18): 100%|██████████| 70/70 [26:09<00:00, 22.42s/it]



Loss: 1.4032005667686462
Policy Loss 0.5381133556365967
Value Loss 0.8650872111320496
5 batches processed
Examples:
tensor([0.0320, 0.0318, 0.0291, 0.0318, 0.0331, 0.0296, 0.0298, 0.0355, 0.0294,
        0.0309, 0.0342, 0.0336, 0.0319, 0.0336, 0.0311, 0.0305, 0.0311, 0.0315,
        0.0303, 0.0307, 0.0334, 0.0348, 0.0264, 0.0310, 0.0337, 0.0309, 0.0374,
        0.0331, 0.0313, 0.0374, 0.0391, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000])
tensor([0.8978, 0.0020, 0.0000, 0.0040, 0.0100, 0.0000, 0.0000, 0.0040, 0.0000,
        0.0120, 0.0160, 0.0040, 0.0020, 0.0040, 0.0040, 0.0020, 0.0000, 0.0020,
        0.0000, 0.0020, 0.0040, 0.0040, 0.0000, 0.0000, 0.0060, 0.0000, 0.0040,
        0.0040, 0.0040, 0.0060, 0.0020, 0.0000, 0.0000, 0.0000, 0.


(Game length:20): 100%|██████████| 70/70 [26:54<00:00, 23.07s/it]



Loss: 1.3801751792430879
Policy Loss 0.5039259016513824
Value Loss 0.8762492775917053
5 batches processed
Examples:
tensor([0.3022, 0.0504, 0.0658, 0.0501, 0.0519, 0.0302, 0.0266, 0.0337, 0.0244,
        0.0288, 0.0754, 0.0188, 0.0895, 0.0156, 0.0142, 0.1222, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000])
tensor([0.0401, 0.0521, 0.0020, 0.0982, 0.6072, 0.0361, 0.0160, 0.0020, 0.0060,
        0.0020, 0.0281, 0.0321, 0.0200, 0.0261, 0.0080, 0.0240, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.


(Game length:35): 100%|██████████| 70/70 [30:11<00:00, 25.87s/it]



Loss: 1.4687478939692178
Policy Loss 0.5521951615810394
Value Loss 0.9165527323881785
6 batches processed
Examples:
tensor([0.0688, 0.0549, 0.0644, 0.0751, 0.0532, 0.0505, 0.0689, 0.0760, 0.0629,
        0.0733, 0.0657, 0.0772, 0.0640, 0.0725, 0.0725, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([0.0100, 0.0180, 0.0120, 0.0020, 0.0160, 0.0100, 0.0240, 0.7315, 0.0080,
        0.0020, 0.0160, 0.0361, 0.0020, 0.0441, 0.0681, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.


(Game length:0):   0%|          | 0/70 [00:00<?, ?it/s]

KeyboardInterrupt: 